// Generated by gencpp from file ainex_interfaces/ColorsDetect.msg
// DO NOT EDIT!


#ifndef AINEX_INTERFACES_MESSAGE_COLORSDETECT_H
#define AINEX_INTERFACES_MESSAGE_COLORSDETECT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ainex_interfaces/ColorDetect.h>

namespace ainex_interfaces
{
template <class ContainerAllocator>
struct ColorsDetect_
{
  typedef ColorsDetect_<ContainerAllocator> Type;

  ColorsDetect_()
    : data()  {
    }
  ColorsDetect_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::ainex_interfaces::ColorDetect_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::ainex_interfaces::ColorDetect_<ContainerAllocator> >> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::ainex_interfaces::ColorsDetect_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ainex_interfaces::ColorsDetect_<ContainerAllocator> const> ConstPtr;

}; // struct ColorsDetect_

typedef ::ainex_interfaces::ColorsDetect_<std::allocator<void> > ColorsDetect;

typedef boost::shared_ptr< ::ainex_interfaces::ColorsDetect > ColorsDetectPtr;
typedef boost::shared_ptr< ::ainex_interfaces::ColorsDetect const> ColorsDetectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ainex_interfaces::ColorsDetect_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ainex_interfaces::ColorsDetect_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ainex_interfaces::ColorsDetect_<ContainerAllocator1> & lhs, const ::ainex_interfaces::ColorsDetect_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ainex_interfaces::ColorsDetect_<ContainerAllocator1> & lhs, const ::ainex_interfaces::ColorsDetect_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ainex_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ainex_interfaces::ColorsDetect_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainex_interfaces::ColorsDetect_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainex_interfaces::ColorsDetect_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainex_interfaces::ColorsDetect_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainex_interfaces::ColorsDetect_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainex_interfaces::ColorsDetect_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ainex_interfaces::ColorsDetect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e8024ffa57fcf070b87e6db34ea1620a";
  }

  static const char* value(const ::ainex_interfaces::ColorsDetect_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe8024ffa57fcf070ULL;
  static const uint64_t static_value2 = 0xb87e6db34ea1620aULL;
};

template<class ContainerAllocator>
struct DataType< ::ainex_interfaces::ColorsDetect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ainex_interfaces/ColorsDetect";
  }

  static const char* value(const ::ainex_interfaces::ColorsDetect_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ainex_interfaces::ColorsDetect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ainex_interfaces/ColorDetect[] data\n"
"\n"
"================================================================================\n"
"MSG: ainex_interfaces/ColorDetect\n"
"string color_name\n"
"bool use_name\n"
"string detect_type\n"
"ainex_interfaces/ROI roi\n"
"ainex_interfaces/LineROI line_roi\n"
"uint32[] image_process_size\n"
"int16[] lab_min\n"
"int16[] lab_max\n"
"float64 min_area\n"
"float64 max_area\n"
"\n"
"================================================================================\n"
"MSG: ainex_interfaces/ROI\n"
"int32 y_min\n"
"int32 y_max\n"
"int32 x_min\n"
"int32 x_max\n"
"\n"
"================================================================================\n"
"MSG: ainex_interfaces/LineROI\n"
"ainex_interfaces/ROI up\n"
"ainex_interfaces/ROI center\n"
"ainex_interfaces/ROI down\n"
;
  }

  static const char* value(const ::ainex_interfaces::ColorsDetect_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ainex_interfaces::ColorsDetect_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ColorsDetect_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ainex_interfaces::ColorsDetect_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ainex_interfaces::ColorsDetect_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ainex_interfaces::ColorDetect_<ContainerAllocator> >::stream(s, indent + "    ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AINEX_INTERFACES_MESSAGE_COLORSDETECT_H
