// Generated by gencpp from file ainex_interfaces/ColorDetect.msg
// DO NOT EDIT!


#ifndef AINEX_INTERFACES_MESSAGE_COLORDETECT_H
#define AINEX_INTERFACES_MESSAGE_COLORDETECT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ainex_interfaces/ROI.h>
#include <ainex_interfaces/LineROI.h>

namespace ainex_interfaces
{
template <class ContainerAllocator>
struct ColorDetect_
{
  typedef ColorDetect_<ContainerAllocator> Type;

  ColorDetect_()
    : color_name()
    , use_name(false)
    , detect_type()
    , roi()
    , line_roi()
    , image_process_size()
    , lab_min()
    , lab_max()
    , min_area(0.0)
    , max_area(0.0)  {
    }
  ColorDetect_(const ContainerAllocator& _alloc)
    : color_name(_alloc)
    , use_name(false)
    , detect_type(_alloc)
    , roi(_alloc)
    , line_roi(_alloc)
    , image_process_size(_alloc)
    , lab_min(_alloc)
    , lab_max(_alloc)
    , min_area(0.0)
    , max_area(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _color_name_type;
  _color_name_type color_name;

   typedef uint8_t _use_name_type;
  _use_name_type use_name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _detect_type_type;
  _detect_type_type detect_type;

   typedef  ::ainex_interfaces::ROI_<ContainerAllocator>  _roi_type;
  _roi_type roi;

   typedef  ::ainex_interfaces::LineROI_<ContainerAllocator>  _line_roi_type;
  _line_roi_type line_roi;

   typedef std::vector<uint32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint32_t>> _image_process_size_type;
  _image_process_size_type image_process_size;

   typedef std::vector<int16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int16_t>> _lab_min_type;
  _lab_min_type lab_min;

   typedef std::vector<int16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int16_t>> _lab_max_type;
  _lab_max_type lab_max;

   typedef double _min_area_type;
  _min_area_type min_area;

   typedef double _max_area_type;
  _max_area_type max_area;





  typedef boost::shared_ptr< ::ainex_interfaces::ColorDetect_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ainex_interfaces::ColorDetect_<ContainerAllocator> const> ConstPtr;

}; // struct ColorDetect_

typedef ::ainex_interfaces::ColorDetect_<std::allocator<void> > ColorDetect;

typedef boost::shared_ptr< ::ainex_interfaces::ColorDetect > ColorDetectPtr;
typedef boost::shared_ptr< ::ainex_interfaces::ColorDetect const> ColorDetectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ainex_interfaces::ColorDetect_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ainex_interfaces::ColorDetect_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ainex_interfaces::ColorDetect_<ContainerAllocator1> & lhs, const ::ainex_interfaces::ColorDetect_<ContainerAllocator2> & rhs)
{
  return lhs.color_name == rhs.color_name &&
    lhs.use_name == rhs.use_name &&
    lhs.detect_type == rhs.detect_type &&
    lhs.roi == rhs.roi &&
    lhs.line_roi == rhs.line_roi &&
    lhs.image_process_size == rhs.image_process_size &&
    lhs.lab_min == rhs.lab_min &&
    lhs.lab_max == rhs.lab_max &&
    lhs.min_area == rhs.min_area &&
    lhs.max_area == rhs.max_area;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ainex_interfaces::ColorDetect_<ContainerAllocator1> & lhs, const ::ainex_interfaces::ColorDetect_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ainex_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ainex_interfaces::ColorDetect_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainex_interfaces::ColorDetect_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainex_interfaces::ColorDetect_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainex_interfaces::ColorDetect_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainex_interfaces::ColorDetect_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainex_interfaces::ColorDetect_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ainex_interfaces::ColorDetect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7c6d76275e561b8430ce7facd08f9909";
  }

  static const char* value(const ::ainex_interfaces::ColorDetect_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7c6d76275e561b84ULL;
  static const uint64_t static_value2 = 0x30ce7facd08f9909ULL;
};

template<class ContainerAllocator>
struct DataType< ::ainex_interfaces::ColorDetect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ainex_interfaces/ColorDetect";
  }

  static const char* value(const ::ainex_interfaces::ColorDetect_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ainex_interfaces::ColorDetect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string color_name\n"
"bool use_name\n"
"string detect_type\n"
"ainex_interfaces/ROI roi\n"
"ainex_interfaces/LineROI line_roi\n"
"uint32[] image_process_size\n"
"int16[] lab_min\n"
"int16[] lab_max\n"
"float64 min_area\n"
"float64 max_area\n"
"\n"
"================================================================================\n"
"MSG: ainex_interfaces/ROI\n"
"int32 y_min\n"
"int32 y_max\n"
"int32 x_min\n"
"int32 x_max\n"
"\n"
"================================================================================\n"
"MSG: ainex_interfaces/LineROI\n"
"ainex_interfaces/ROI up\n"
"ainex_interfaces/ROI center\n"
"ainex_interfaces/ROI down\n"
;
  }

  static const char* value(const ::ainex_interfaces::ColorDetect_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ainex_interfaces::ColorDetect_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.color_name);
      stream.next(m.use_name);
      stream.next(m.detect_type);
      stream.next(m.roi);
      stream.next(m.line_roi);
      stream.next(m.image_process_size);
      stream.next(m.lab_min);
      stream.next(m.lab_max);
      stream.next(m.min_area);
      stream.next(m.max_area);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ColorDetect_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ainex_interfaces::ColorDetect_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ainex_interfaces::ColorDetect_<ContainerAllocator>& v)
  {
    s << indent << "color_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.color_name);
    s << indent << "use_name: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.use_name);
    s << indent << "detect_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.detect_type);
    s << indent << "roi: ";
    s << std::endl;
    Printer< ::ainex_interfaces::ROI_<ContainerAllocator> >::stream(s, indent + "  ", v.roi);
    s << indent << "line_roi: ";
    s << std::endl;
    Printer< ::ainex_interfaces::LineROI_<ContainerAllocator> >::stream(s, indent + "  ", v.line_roi);
    s << indent << "image_process_size[]" << std::endl;
    for (size_t i = 0; i < v.image_process_size.size(); ++i)
    {
      s << indent << "  image_process_size[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.image_process_size[i]);
    }
    s << indent << "lab_min[]" << std::endl;
    for (size_t i = 0; i < v.lab_min.size(); ++i)
    {
      s << indent << "  lab_min[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.lab_min[i]);
    }
    s << indent << "lab_max[]" << std::endl;
    for (size_t i = 0; i < v.lab_max.size(); ++i)
    {
      s << indent << "  lab_max[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.lab_max[i]);
    }
    s << indent << "min_area: ";
    Printer<double>::stream(s, indent + "  ", v.min_area);
    s << indent << "max_area: ";
    Printer<double>::stream(s, indent + "  ", v.max_area);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AINEX_INTERFACES_MESSAGE_COLORDETECT_H
