// Generated by gencpp from file ainex_interfaces/FingerPosition.msg
// DO NOT EDIT!


#ifndef AINEX_INTERFACES_MESSAGE_FINGERPOSITION_H
#define AINEX_INTERFACES_MESSAGE_FINGERPOSITION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <ainex_interfaces/PixelPosition.h>

namespace ainex_interfaces
{
template <class ContainerAllocator>
struct FingerPosition_
{
  typedef FingerPosition_<ContainerAllocator> Type;

  FingerPosition_()
    : header()
    , label()
    , points()  {
    }
  FingerPosition_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , label(_alloc)
    , points(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _label_type;
  _label_type label;

   typedef  ::ainex_interfaces::PixelPosition_<ContainerAllocator>  _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::ainex_interfaces::FingerPosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ainex_interfaces::FingerPosition_<ContainerAllocator> const> ConstPtr;

}; // struct FingerPosition_

typedef ::ainex_interfaces::FingerPosition_<std::allocator<void> > FingerPosition;

typedef boost::shared_ptr< ::ainex_interfaces::FingerPosition > FingerPositionPtr;
typedef boost::shared_ptr< ::ainex_interfaces::FingerPosition const> FingerPositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ainex_interfaces::FingerPosition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ainex_interfaces::FingerPosition_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ainex_interfaces::FingerPosition_<ContainerAllocator1> & lhs, const ::ainex_interfaces::FingerPosition_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.label == rhs.label &&
    lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ainex_interfaces::FingerPosition_<ContainerAllocator1> & lhs, const ::ainex_interfaces::FingerPosition_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ainex_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ainex_interfaces::FingerPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainex_interfaces::FingerPosition_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainex_interfaces::FingerPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainex_interfaces::FingerPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainex_interfaces::FingerPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainex_interfaces::FingerPosition_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ainex_interfaces::FingerPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e758c8d7096fb5f61363fb7d7418aeb1";
  }

  static const char* value(const ::ainex_interfaces::FingerPosition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe758c8d7096fb5f6ULL;
  static const uint64_t static_value2 = 0x1363fb7d7418aeb1ULL;
};

template<class ContainerAllocator>
struct DataType< ::ainex_interfaces::FingerPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ainex_interfaces/FingerPosition";
  }

  static const char* value(const ::ainex_interfaces::FingerPosition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ainex_interfaces::FingerPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"string label\n"
"ainex_interfaces/PixelPosition points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: ainex_interfaces/PixelPosition\n"
"float64 x\n"
"float64 y\n"
;
  }

  static const char* value(const ::ainex_interfaces::FingerPosition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ainex_interfaces::FingerPosition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.label);
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FingerPosition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ainex_interfaces::FingerPosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ainex_interfaces::FingerPosition_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.label);
    s << indent << "points: ";
    s << std::endl;
    Printer< ::ainex_interfaces::PixelPosition_<ContainerAllocator> >::stream(s, indent + "  ", v.points);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AINEX_INTERFACES_MESSAGE_FINGERPOSITION_H
