// Generated by gencpp from file ainex_interfaces/GetWalkingStateResponse.msg
// DO NOT EDIT!


#ifndef AINEX_INTERFACES_MESSAGE_GETWALKINGSTATERESPONSE_H
#define AINEX_INTERFACES_MESSAGE_GETWALKINGSTATERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ainex_interfaces
{
template <class ContainerAllocator>
struct GetWalkingStateResponse_
{
  typedef GetWalkingStateResponse_<ContainerAllocator> Type;

  GetWalkingStateResponse_()
    : state(false)
    , message()  {
    }
  GetWalkingStateResponse_(const ContainerAllocator& _alloc)
    : state(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _state_type;
  _state_type state;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::ainex_interfaces::GetWalkingStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ainex_interfaces::GetWalkingStateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetWalkingStateResponse_

typedef ::ainex_interfaces::GetWalkingStateResponse_<std::allocator<void> > GetWalkingStateResponse;

typedef boost::shared_ptr< ::ainex_interfaces::GetWalkingStateResponse > GetWalkingStateResponsePtr;
typedef boost::shared_ptr< ::ainex_interfaces::GetWalkingStateResponse const> GetWalkingStateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ainex_interfaces::GetWalkingStateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ainex_interfaces::GetWalkingStateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ainex_interfaces::GetWalkingStateResponse_<ContainerAllocator1> & lhs, const ::ainex_interfaces::GetWalkingStateResponse_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ainex_interfaces::GetWalkingStateResponse_<ContainerAllocator1> & lhs, const ::ainex_interfaces::GetWalkingStateResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ainex_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ainex_interfaces::GetWalkingStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainex_interfaces::GetWalkingStateResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainex_interfaces::GetWalkingStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainex_interfaces::GetWalkingStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainex_interfaces::GetWalkingStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainex_interfaces::GetWalkingStateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ainex_interfaces::GetWalkingStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "603c04acee08adec382920a1d1b74bb8";
  }

  static const char* value(const ::ainex_interfaces::GetWalkingStateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x603c04acee08adecULL;
  static const uint64_t static_value2 = 0x382920a1d1b74bb8ULL;
};

template<class ContainerAllocator>
struct DataType< ::ainex_interfaces::GetWalkingStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ainex_interfaces/GetWalkingStateResponse";
  }

  static const char* value(const ::ainex_interfaces::GetWalkingStateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ainex_interfaces::GetWalkingStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool state\n"
"string message\n"
"\n"
"\n"
;
  }

  static const char* value(const ::ainex_interfaces::GetWalkingStateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ainex_interfaces::GetWalkingStateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetWalkingStateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ainex_interfaces::GetWalkingStateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ainex_interfaces::GetWalkingStateResponse_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AINEX_INTERFACES_MESSAGE_GETWALKINGSTATERESPONSE_H
