// Generated by gencpp from file ainex_interfaces/GetWalkingState.msg
// DO NOT EDIT!


#ifndef AINEX_INTERFACES_MESSAGE_GETWALKINGSTATE_H
#define AINEX_INTERFACES_MESSAGE_GETWALKINGSTATE_H

#include <ros/service_traits.h>


#include <ainex_interfaces/GetWalkingStateRequest.h>
#include <ainex_interfaces/GetWalkingStateResponse.h>


namespace ainex_interfaces
{

struct GetWalkingState
{

typedef GetWalkingStateRequest Request;
typedef GetWalkingStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetWalkingState
} // namespace ainex_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ainex_interfaces::GetWalkingState > {
  static const char* value()
  {
    return "603c04acee08adec382920a1d1b74bb8";
  }

  static const char* value(const ::ainex_interfaces::GetWalkingState&) { return value(); }
};

template<>
struct DataType< ::ainex_interfaces::GetWalkingState > {
  static const char* value()
  {
    return "ainex_interfaces/GetWalkingState";
  }

  static const char* value(const ::ainex_interfaces::GetWalkingState&) { return value(); }
};


// service_traits::MD5Sum< ::ainex_interfaces::GetWalkingStateRequest> should match
// service_traits::MD5Sum< ::ainex_interfaces::GetWalkingState >
template<>
struct MD5Sum< ::ainex_interfaces::GetWalkingStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ainex_interfaces::GetWalkingState >::value();
  }
  static const char* value(const ::ainex_interfaces::GetWalkingStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ainex_interfaces::GetWalkingStateRequest> should match
// service_traits::DataType< ::ainex_interfaces::GetWalkingState >
template<>
struct DataType< ::ainex_interfaces::GetWalkingStateRequest>
{
  static const char* value()
  {
    return DataType< ::ainex_interfaces::GetWalkingState >::value();
  }
  static const char* value(const ::ainex_interfaces::GetWalkingStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ainex_interfaces::GetWalkingStateResponse> should match
// service_traits::MD5Sum< ::ainex_interfaces::GetWalkingState >
template<>
struct MD5Sum< ::ainex_interfaces::GetWalkingStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ainex_interfaces::GetWalkingState >::value();
  }
  static const char* value(const ::ainex_interfaces::GetWalkingStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ainex_interfaces::GetWalkingStateResponse> should match
// service_traits::DataType< ::ainex_interfaces::GetWalkingState >
template<>
struct DataType< ::ainex_interfaces::GetWalkingStateResponse>
{
  static const char* value()
  {
    return DataType< ::ainex_interfaces::GetWalkingState >::value();
  }
  static const char* value(const ::ainex_interfaces::GetWalkingStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AINEX_INTERFACES_MESSAGE_GETWALKINGSTATE_H
