// Generated by gencpp from file ainex_interfaces/GetWalkingStateRequest.msg
// DO NOT EDIT!


#ifndef AINEX_INTERFACES_MESSAGE_GETWALKINGSTATEREQUEST_H
#define AINEX_INTERFACES_MESSAGE_GETWALKINGSTATEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ainex_interfaces
{
template <class ContainerAllocator>
struct GetWalkingStateRequest_
{
  typedef GetWalkingStateRequest_<ContainerAllocator> Type;

  GetWalkingStateRequest_()
    {
    }
  GetWalkingStateRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::ainex_interfaces::GetWalkingStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ainex_interfaces::GetWalkingStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetWalkingStateRequest_

typedef ::ainex_interfaces::GetWalkingStateRequest_<std::allocator<void> > GetWalkingStateRequest;

typedef boost::shared_ptr< ::ainex_interfaces::GetWalkingStateRequest > GetWalkingStateRequestPtr;
typedef boost::shared_ptr< ::ainex_interfaces::GetWalkingStateRequest const> GetWalkingStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ainex_interfaces::GetWalkingStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ainex_interfaces::GetWalkingStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace ainex_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ainex_interfaces::GetWalkingStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainex_interfaces::GetWalkingStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainex_interfaces::GetWalkingStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainex_interfaces::GetWalkingStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainex_interfaces::GetWalkingStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainex_interfaces::GetWalkingStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ainex_interfaces::GetWalkingStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::ainex_interfaces::GetWalkingStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::ainex_interfaces::GetWalkingStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ainex_interfaces/GetWalkingStateRequest";
  }

  static const char* value(const ::ainex_interfaces::GetWalkingStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ainex_interfaces::GetWalkingStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::ainex_interfaces::GetWalkingStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ainex_interfaces::GetWalkingStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetWalkingStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ainex_interfaces::GetWalkingStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::ainex_interfaces::GetWalkingStateRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // AINEX_INTERFACES_MESSAGE_GETWALKINGSTATEREQUEST_H
