// Generated by gencpp from file ainex_interfaces/GetWalkingParam.msg
// DO NOT EDIT!


#ifndef AINEX_INTERFACES_MESSAGE_GETWALKINGPARAM_H
#define AINEX_INTERFACES_MESSAGE_GETWALKINGPARAM_H

#include <ros/service_traits.h>


#include <ainex_interfaces/GetWalkingParamRequest.h>
#include <ainex_interfaces/GetWalkingParamResponse.h>


namespace ainex_interfaces
{

struct GetWalkingParam
{

typedef GetWalkingParamRequest Request;
typedef GetWalkingParamResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetWalkingParam
} // namespace ainex_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ainex_interfaces::GetWalkingParam > {
  static const char* value()
  {
    return "eb0635e28cd7c7a73020918163e1e751";
  }

  static const char* value(const ::ainex_interfaces::GetWalkingParam&) { return value(); }
};

template<>
struct DataType< ::ainex_interfaces::GetWalkingParam > {
  static const char* value()
  {
    return "ainex_interfaces/GetWalkingParam";
  }

  static const char* value(const ::ainex_interfaces::GetWalkingParam&) { return value(); }
};


// service_traits::MD5Sum< ::ainex_interfaces::GetWalkingParamRequest> should match
// service_traits::MD5Sum< ::ainex_interfaces::GetWalkingParam >
template<>
struct MD5Sum< ::ainex_interfaces::GetWalkingParamRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ainex_interfaces::GetWalkingParam >::value();
  }
  static const char* value(const ::ainex_interfaces::GetWalkingParamRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ainex_interfaces::GetWalkingParamRequest> should match
// service_traits::DataType< ::ainex_interfaces::GetWalkingParam >
template<>
struct DataType< ::ainex_interfaces::GetWalkingParamRequest>
{
  static const char* value()
  {
    return DataType< ::ainex_interfaces::GetWalkingParam >::value();
  }
  static const char* value(const ::ainex_interfaces::GetWalkingParamRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ainex_interfaces::GetWalkingParamResponse> should match
// service_traits::MD5Sum< ::ainex_interfaces::GetWalkingParam >
template<>
struct MD5Sum< ::ainex_interfaces::GetWalkingParamResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ainex_interfaces::GetWalkingParam >::value();
  }
  static const char* value(const ::ainex_interfaces::GetWalkingParamResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ainex_interfaces::GetWalkingParamResponse> should match
// service_traits::DataType< ::ainex_interfaces::GetWalkingParam >
template<>
struct DataType< ::ainex_interfaces::GetWalkingParamResponse>
{
  static const char* value()
  {
    return DataType< ::ainex_interfaces::GetWalkingParam >::value();
  }
  static const char* value(const ::ainex_interfaces::GetWalkingParamResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AINEX_INTERFACES_MESSAGE_GETWALKINGPARAM_H
