// Generated by gencpp from file ainex_interfaces/GetWalkingParamResponse.msg
// DO NOT EDIT!


#ifndef AINEX_INTERFACES_MESSAGE_GETWALKINGPARAMRESPONSE_H
#define AINEX_INTERFACES_MESSAGE_GETWALKINGPARAMRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ainex_interfaces/WalkingParam.h>

namespace ainex_interfaces
{
template <class ContainerAllocator>
struct GetWalkingParamResponse_
{
  typedef GetWalkingParamResponse_<ContainerAllocator> Type;

  GetWalkingParamResponse_()
    : parameters()  {
    }
  GetWalkingParamResponse_(const ContainerAllocator& _alloc)
    : parameters(_alloc)  {
  (void)_alloc;
    }



   typedef  ::ainex_interfaces::WalkingParam_<ContainerAllocator>  _parameters_type;
  _parameters_type parameters;





  typedef boost::shared_ptr< ::ainex_interfaces::GetWalkingParamResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ainex_interfaces::GetWalkingParamResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetWalkingParamResponse_

typedef ::ainex_interfaces::GetWalkingParamResponse_<std::allocator<void> > GetWalkingParamResponse;

typedef boost::shared_ptr< ::ainex_interfaces::GetWalkingParamResponse > GetWalkingParamResponsePtr;
typedef boost::shared_ptr< ::ainex_interfaces::GetWalkingParamResponse const> GetWalkingParamResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ainex_interfaces::GetWalkingParamResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ainex_interfaces::GetWalkingParamResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ainex_interfaces::GetWalkingParamResponse_<ContainerAllocator1> & lhs, const ::ainex_interfaces::GetWalkingParamResponse_<ContainerAllocator2> & rhs)
{
  return lhs.parameters == rhs.parameters;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ainex_interfaces::GetWalkingParamResponse_<ContainerAllocator1> & lhs, const ::ainex_interfaces::GetWalkingParamResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ainex_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ainex_interfaces::GetWalkingParamResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainex_interfaces::GetWalkingParamResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainex_interfaces::GetWalkingParamResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainex_interfaces::GetWalkingParamResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainex_interfaces::GetWalkingParamResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainex_interfaces::GetWalkingParamResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ainex_interfaces::GetWalkingParamResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7ff8a6c050957bd548b46c0a7b638966";
  }

  static const char* value(const ::ainex_interfaces::GetWalkingParamResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7ff8a6c050957bd5ULL;
  static const uint64_t static_value2 = 0x48b46c0a7b638966ULL;
};

template<class ContainerAllocator>
struct DataType< ::ainex_interfaces::GetWalkingParamResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ainex_interfaces/GetWalkingParamResponse";
  }

  static const char* value(const ::ainex_interfaces::GetWalkingParamResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ainex_interfaces::GetWalkingParamResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "WalkingParam    parameters\n"
"\n"
"================================================================================\n"
"MSG: ainex_interfaces/WalkingParam\n"
"####### walking init pose #######\n"
"float32 init_x_offset\n"
"float32 init_y_offset\n"
"float32 init_z_offset\n"
"float32 init_roll_offset\n"
"float32 init_pitch_offset\n"
"float32 init_yaw_offset\n"
"\n"
"####### time parameter #####\n"
"float32 period_time\n"
"float32 dsp_ratio\n"
"float32 step_fb_ratio\n"
"uint32 period_times\n"
"\n"
"########## walking parameter ########\n"
"float32 x_move_amplitude\n"
"float32 y_move_amplitude\n"
"float32 z_move_amplitude\n"
"float32 angle_move_amplitude\n"
"bool move_aim_on\n"
"float32 arm_swing_gain\n"
"float32 y_swap_amplitude\n"
"float32 z_swap_amplitude\n"
"float32 pelvis_offset\n"
"float32 hip_pitch_offset\n"
;
  }

  static const char* value(const ::ainex_interfaces::GetWalkingParamResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ainex_interfaces::GetWalkingParamResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.parameters);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetWalkingParamResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ainex_interfaces::GetWalkingParamResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ainex_interfaces::GetWalkingParamResponse_<ContainerAllocator>& v)
  {
    s << indent << "parameters: ";
    s << std::endl;
    Printer< ::ainex_interfaces::WalkingParam_<ContainerAllocator> >::stream(s, indent + "  ", v.parameters);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AINEX_INTERFACES_MESSAGE_GETWALKINGPARAMRESPONSE_H
