// Generated by gencpp from file ainex_interfaces/LineROI.msg
// DO NOT EDIT!


#ifndef AINEX_INTERFACES_MESSAGE_LINEROI_H
#define AINEX_INTERFACES_MESSAGE_LINEROI_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ainex_interfaces/ROI.h>
#include <ainex_interfaces/ROI.h>
#include <ainex_interfaces/ROI.h>

namespace ainex_interfaces
{
template <class ContainerAllocator>
struct LineROI_
{
  typedef LineROI_<ContainerAllocator> Type;

  LineROI_()
    : up()
    , center()
    , down()  {
    }
  LineROI_(const ContainerAllocator& _alloc)
    : up(_alloc)
    , center(_alloc)
    , down(_alloc)  {
  (void)_alloc;
    }



   typedef  ::ainex_interfaces::ROI_<ContainerAllocator>  _up_type;
  _up_type up;

   typedef  ::ainex_interfaces::ROI_<ContainerAllocator>  _center_type;
  _center_type center;

   typedef  ::ainex_interfaces::ROI_<ContainerAllocator>  _down_type;
  _down_type down;





  typedef boost::shared_ptr< ::ainex_interfaces::LineROI_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ainex_interfaces::LineROI_<ContainerAllocator> const> ConstPtr;

}; // struct LineROI_

typedef ::ainex_interfaces::LineROI_<std::allocator<void> > LineROI;

typedef boost::shared_ptr< ::ainex_interfaces::LineROI > LineROIPtr;
typedef boost::shared_ptr< ::ainex_interfaces::LineROI const> LineROIConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ainex_interfaces::LineROI_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ainex_interfaces::LineROI_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ainex_interfaces::LineROI_<ContainerAllocator1> & lhs, const ::ainex_interfaces::LineROI_<ContainerAllocator2> & rhs)
{
  return lhs.up == rhs.up &&
    lhs.center == rhs.center &&
    lhs.down == rhs.down;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ainex_interfaces::LineROI_<ContainerAllocator1> & lhs, const ::ainex_interfaces::LineROI_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ainex_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ainex_interfaces::LineROI_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainex_interfaces::LineROI_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainex_interfaces::LineROI_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainex_interfaces::LineROI_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainex_interfaces::LineROI_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainex_interfaces::LineROI_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ainex_interfaces::LineROI_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bccdc6e8e70cb622e1827d4df83b58fa";
  }

  static const char* value(const ::ainex_interfaces::LineROI_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbccdc6e8e70cb622ULL;
  static const uint64_t static_value2 = 0xe1827d4df83b58faULL;
};

template<class ContainerAllocator>
struct DataType< ::ainex_interfaces::LineROI_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ainex_interfaces/LineROI";
  }

  static const char* value(const ::ainex_interfaces::LineROI_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ainex_interfaces::LineROI_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ainex_interfaces/ROI up\n"
"ainex_interfaces/ROI center\n"
"ainex_interfaces/ROI down\n"
"\n"
"================================================================================\n"
"MSG: ainex_interfaces/ROI\n"
"int32 y_min\n"
"int32 y_max\n"
"int32 x_min\n"
"int32 x_max\n"
;
  }

  static const char* value(const ::ainex_interfaces::LineROI_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ainex_interfaces::LineROI_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.up);
      stream.next(m.center);
      stream.next(m.down);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LineROI_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ainex_interfaces::LineROI_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ainex_interfaces::LineROI_<ContainerAllocator>& v)
  {
    s << indent << "up: ";
    s << std::endl;
    Printer< ::ainex_interfaces::ROI_<ContainerAllocator> >::stream(s, indent + "  ", v.up);
    s << indent << "center: ";
    s << std::endl;
    Printer< ::ainex_interfaces::ROI_<ContainerAllocator> >::stream(s, indent + "  ", v.center);
    s << indent << "down: ";
    s << std::endl;
    Printer< ::ainex_interfaces::ROI_<ContainerAllocator> >::stream(s, indent + "  ", v.down);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AINEX_INTERFACES_MESSAGE_LINEROI_H
