// Generated by gencpp from file ainex_interfaces/ObjectInfo.msg
// DO NOT EDIT!


#ifndef AINEX_INTERFACES_MESSAGE_OBJECTINFO_H
#define AINEX_INTERFACES_MESSAGE_OBJECTINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ainex_interfaces
{
template <class ContainerAllocator>
struct ObjectInfo_
{
  typedef ObjectInfo_<ContainerAllocator> Type;

  ObjectInfo_()
    : label()
    , type()
    , width(0)
    , height(0)
    , x(0)
    , y(0)
    , radius(0)
    , angle(0)
    , left_point()
    , right_point()  {
    }
  ObjectInfo_(const ContainerAllocator& _alloc)
    : label(_alloc)
    , type(_alloc)
    , width(0)
    , height(0)
    , x(0)
    , y(0)
    , radius(0)
    , angle(0)
    , left_point(_alloc)
    , right_point(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _label_type;
  _label_type label;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _type_type;
  _type_type type;

   typedef int32_t _width_type;
  _width_type width;

   typedef int32_t _height_type;
  _height_type height;

   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;

   typedef int32_t _radius_type;
  _radius_type radius;

   typedef int32_t _angle_type;
  _angle_type angle;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _left_point_type;
  _left_point_type left_point;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _right_point_type;
  _right_point_type right_point;





  typedef boost::shared_ptr< ::ainex_interfaces::ObjectInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ainex_interfaces::ObjectInfo_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectInfo_

typedef ::ainex_interfaces::ObjectInfo_<std::allocator<void> > ObjectInfo;

typedef boost::shared_ptr< ::ainex_interfaces::ObjectInfo > ObjectInfoPtr;
typedef boost::shared_ptr< ::ainex_interfaces::ObjectInfo const> ObjectInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ainex_interfaces::ObjectInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ainex_interfaces::ObjectInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ainex_interfaces::ObjectInfo_<ContainerAllocator1> & lhs, const ::ainex_interfaces::ObjectInfo_<ContainerAllocator2> & rhs)
{
  return lhs.label == rhs.label &&
    lhs.type == rhs.type &&
    lhs.width == rhs.width &&
    lhs.height == rhs.height &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.radius == rhs.radius &&
    lhs.angle == rhs.angle &&
    lhs.left_point == rhs.left_point &&
    lhs.right_point == rhs.right_point;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ainex_interfaces::ObjectInfo_<ContainerAllocator1> & lhs, const ::ainex_interfaces::ObjectInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ainex_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ainex_interfaces::ObjectInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainex_interfaces::ObjectInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainex_interfaces::ObjectInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainex_interfaces::ObjectInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainex_interfaces::ObjectInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainex_interfaces::ObjectInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ainex_interfaces::ObjectInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0cbea474c999c4405c07e8a92c8435fc";
  }

  static const char* value(const ::ainex_interfaces::ObjectInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0cbea474c999c440ULL;
  static const uint64_t static_value2 = 0x5c07e8a92c8435fcULL;
};

template<class ContainerAllocator>
struct DataType< ::ainex_interfaces::ObjectInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ainex_interfaces/ObjectInfo";
  }

  static const char* value(const ::ainex_interfaces::ObjectInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ainex_interfaces::ObjectInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string label\n"
"string type\n"
"int32 width\n"
"int32 height\n"
"int32 x\n"
"int32 y\n"
"int32 radius\n"
"int32 angle\n"
"int32[] left_point\n"
"int32[] right_point\n"
;
  }

  static const char* value(const ::ainex_interfaces::ObjectInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ainex_interfaces::ObjectInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.label);
      stream.next(m.type);
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.radius);
      stream.next(m.angle);
      stream.next(m.left_point);
      stream.next(m.right_point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ainex_interfaces::ObjectInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ainex_interfaces::ObjectInfo_<ContainerAllocator>& v)
  {
    s << indent << "label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.label);
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.type);
    s << indent << "width: ";
    Printer<int32_t>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<int32_t>::stream(s, indent + "  ", v.height);
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "radius: ";
    Printer<int32_t>::stream(s, indent + "  ", v.radius);
    s << indent << "angle: ";
    Printer<int32_t>::stream(s, indent + "  ", v.angle);
    s << indent << "left_point[]" << std::endl;
    for (size_t i = 0; i < v.left_point.size(); ++i)
    {
      s << indent << "  left_point[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.left_point[i]);
    }
    s << indent << "right_point[]" << std::endl;
    for (size_t i = 0; i < v.right_point.size(); ++i)
    {
      s << indent << "  right_point[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.right_point[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AINEX_INTERFACES_MESSAGE_OBJECTINFO_H
