// Generated by gencpp from file ainex_interfaces/ObjectsInfo.msg
// DO NOT EDIT!


#ifndef AINEX_INTERFACES_MESSAGE_OBJECTSINFO_H
#define AINEX_INTERFACES_MESSAGE_OBJECTSINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ainex_interfaces/ObjectInfo.h>

namespace ainex_interfaces
{
template <class ContainerAllocator>
struct ObjectsInfo_
{
  typedef ObjectsInfo_<ContainerAllocator> Type;

  ObjectsInfo_()
    : data()  {
    }
  ObjectsInfo_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::ainex_interfaces::ObjectInfo_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::ainex_interfaces::ObjectInfo_<ContainerAllocator> >> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::ainex_interfaces::ObjectsInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ainex_interfaces::ObjectsInfo_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectsInfo_

typedef ::ainex_interfaces::ObjectsInfo_<std::allocator<void> > ObjectsInfo;

typedef boost::shared_ptr< ::ainex_interfaces::ObjectsInfo > ObjectsInfoPtr;
typedef boost::shared_ptr< ::ainex_interfaces::ObjectsInfo const> ObjectsInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ainex_interfaces::ObjectsInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ainex_interfaces::ObjectsInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ainex_interfaces::ObjectsInfo_<ContainerAllocator1> & lhs, const ::ainex_interfaces::ObjectsInfo_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ainex_interfaces::ObjectsInfo_<ContainerAllocator1> & lhs, const ::ainex_interfaces::ObjectsInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ainex_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ainex_interfaces::ObjectsInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainex_interfaces::ObjectsInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainex_interfaces::ObjectsInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainex_interfaces::ObjectsInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainex_interfaces::ObjectsInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainex_interfaces::ObjectsInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ainex_interfaces::ObjectsInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d2fb73326b72ae8d2e6610c8589c196f";
  }

  static const char* value(const ::ainex_interfaces::ObjectsInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd2fb73326b72ae8dULL;
  static const uint64_t static_value2 = 0x2e6610c8589c196fULL;
};

template<class ContainerAllocator>
struct DataType< ::ainex_interfaces::ObjectsInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ainex_interfaces/ObjectsInfo";
  }

  static const char* value(const ::ainex_interfaces::ObjectsInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ainex_interfaces::ObjectsInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return " ainex_interfaces/ObjectInfo[] data\n"
"\n"
"================================================================================\n"
"MSG: ainex_interfaces/ObjectInfo\n"
"string label\n"
"string type\n"
"int32 width\n"
"int32 height\n"
"int32 x\n"
"int32 y\n"
"int32 radius\n"
"int32 angle\n"
"int32[] left_point\n"
"int32[] right_point\n"
;
  }

  static const char* value(const ::ainex_interfaces::ObjectsInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ainex_interfaces::ObjectsInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectsInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ainex_interfaces::ObjectsInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ainex_interfaces::ObjectsInfo_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ainex_interfaces::ObjectInfo_<ContainerAllocator> >::stream(s, indent + "    ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AINEX_INTERFACES_MESSAGE_OBJECTSINFO_H
