// Generated by gencpp from file ainex_interfaces/RGB.msg
// DO NOT EDIT!


#ifndef AINEX_INTERFACES_MESSAGE_RGB_H
#define AINEX_INTERFACES_MESSAGE_RGB_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ainex_interfaces
{
template <class ContainerAllocator>
struct RGB_
{
  typedef RGB_<ContainerAllocator> Type;

  RGB_()
    : r(0)
    , g(0)
    , b(0)  {
    }
  RGB_(const ContainerAllocator& _alloc)
    : r(0)
    , g(0)
    , b(0)  {
  (void)_alloc;
    }



   typedef int16_t _r_type;
  _r_type r;

   typedef int16_t _g_type;
  _g_type g;

   typedef int16_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::ainex_interfaces::RGB_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ainex_interfaces::RGB_<ContainerAllocator> const> ConstPtr;

}; // struct RGB_

typedef ::ainex_interfaces::RGB_<std::allocator<void> > RGB;

typedef boost::shared_ptr< ::ainex_interfaces::RGB > RGBPtr;
typedef boost::shared_ptr< ::ainex_interfaces::RGB const> RGBConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ainex_interfaces::RGB_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ainex_interfaces::RGB_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ainex_interfaces::RGB_<ContainerAllocator1> & lhs, const ::ainex_interfaces::RGB_<ContainerAllocator2> & rhs)
{
  return lhs.r == rhs.r &&
    lhs.g == rhs.g &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ainex_interfaces::RGB_<ContainerAllocator1> & lhs, const ::ainex_interfaces::RGB_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ainex_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ainex_interfaces::RGB_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainex_interfaces::RGB_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainex_interfaces::RGB_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainex_interfaces::RGB_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainex_interfaces::RGB_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainex_interfaces::RGB_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ainex_interfaces::RGB_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2dfe481b7e570e3e4be99cdc0453c9c8";
  }

  static const char* value(const ::ainex_interfaces::RGB_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2dfe481b7e570e3eULL;
  static const uint64_t static_value2 = 0x4be99cdc0453c9c8ULL;
};

template<class ContainerAllocator>
struct DataType< ::ainex_interfaces::RGB_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ainex_interfaces/RGB";
  }

  static const char* value(const ::ainex_interfaces::RGB_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ainex_interfaces::RGB_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 r\n"
"int16 g\n"
"int16 b\n"
;
  }

  static const char* value(const ::ainex_interfaces::RGB_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ainex_interfaces::RGB_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.r);
      stream.next(m.g);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RGB_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ainex_interfaces::RGB_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ainex_interfaces::RGB_<ContainerAllocator>& v)
  {
    s << indent << "r: ";
    Printer<int16_t>::stream(s, indent + "  ", v.r);
    s << indent << "g: ";
    Printer<int16_t>::stream(s, indent + "  ", v.g);
    s << indent << "b: ";
    Printer<int16_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AINEX_INTERFACES_MESSAGE_RGB_H
