// Generated by gencpp from file ainex_interfaces/ROI.msg
// DO NOT EDIT!


#ifndef AINEX_INTERFACES_MESSAGE_ROI_H
#define AINEX_INTERFACES_MESSAGE_ROI_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ainex_interfaces
{
template <class ContainerAllocator>
struct ROI_
{
  typedef ROI_<ContainerAllocator> Type;

  ROI_()
    : y_min(0)
    , y_max(0)
    , x_min(0)
    , x_max(0)  {
    }
  ROI_(const ContainerAllocator& _alloc)
    : y_min(0)
    , y_max(0)
    , x_min(0)
    , x_max(0)  {
  (void)_alloc;
    }



   typedef int32_t _y_min_type;
  _y_min_type y_min;

   typedef int32_t _y_max_type;
  _y_max_type y_max;

   typedef int32_t _x_min_type;
  _x_min_type x_min;

   typedef int32_t _x_max_type;
  _x_max_type x_max;





  typedef boost::shared_ptr< ::ainex_interfaces::ROI_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ainex_interfaces::ROI_<ContainerAllocator> const> ConstPtr;

}; // struct ROI_

typedef ::ainex_interfaces::ROI_<std::allocator<void> > ROI;

typedef boost::shared_ptr< ::ainex_interfaces::ROI > ROIPtr;
typedef boost::shared_ptr< ::ainex_interfaces::ROI const> ROIConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ainex_interfaces::ROI_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ainex_interfaces::ROI_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ainex_interfaces::ROI_<ContainerAllocator1> & lhs, const ::ainex_interfaces::ROI_<ContainerAllocator2> & rhs)
{
  return lhs.y_min == rhs.y_min &&
    lhs.y_max == rhs.y_max &&
    lhs.x_min == rhs.x_min &&
    lhs.x_max == rhs.x_max;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ainex_interfaces::ROI_<ContainerAllocator1> & lhs, const ::ainex_interfaces::ROI_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ainex_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ainex_interfaces::ROI_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainex_interfaces::ROI_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainex_interfaces::ROI_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainex_interfaces::ROI_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainex_interfaces::ROI_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainex_interfaces::ROI_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ainex_interfaces::ROI_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2b00faa7a7bb95e05cfa78034bc38cd9";
  }

  static const char* value(const ::ainex_interfaces::ROI_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2b00faa7a7bb95e0ULL;
  static const uint64_t static_value2 = 0x5cfa78034bc38cd9ULL;
};

template<class ContainerAllocator>
struct DataType< ::ainex_interfaces::ROI_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ainex_interfaces/ROI";
  }

  static const char* value(const ::ainex_interfaces::ROI_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ainex_interfaces::ROI_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 y_min\n"
"int32 y_max\n"
"int32 x_min\n"
"int32 x_max\n"
;
  }

  static const char* value(const ::ainex_interfaces::ROI_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ainex_interfaces::ROI_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.y_min);
      stream.next(m.y_max);
      stream.next(m.x_min);
      stream.next(m.x_max);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ROI_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ainex_interfaces::ROI_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ainex_interfaces::ROI_<ContainerAllocator>& v)
  {
    s << indent << "y_min: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y_min);
    s << indent << "y_max: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y_max);
    s << indent << "x_min: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x_min);
    s << indent << "x_max: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x_max);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AINEX_INTERFACES_MESSAGE_ROI_H
