// Generated by gencpp from file ainex_interfaces/SetFloatRequest.msg
// DO NOT EDIT!


#ifndef AINEX_INTERFACES_MESSAGE_SETFLOATREQUEST_H
#define AINEX_INTERFACES_MESSAGE_SETFLOATREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ainex_interfaces
{
template <class ContainerAllocator>
struct SetFloatRequest_
{
  typedef SetFloatRequest_<ContainerAllocator> Type;

  SetFloatRequest_()
    : data(0.0)  {
    }
  SetFloatRequest_(const ContainerAllocator& _alloc)
    : data(0.0)  {
  (void)_alloc;
    }



   typedef double _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::ainex_interfaces::SetFloatRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ainex_interfaces::SetFloatRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetFloatRequest_

typedef ::ainex_interfaces::SetFloatRequest_<std::allocator<void> > SetFloatRequest;

typedef boost::shared_ptr< ::ainex_interfaces::SetFloatRequest > SetFloatRequestPtr;
typedef boost::shared_ptr< ::ainex_interfaces::SetFloatRequest const> SetFloatRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ainex_interfaces::SetFloatRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ainex_interfaces::SetFloatRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ainex_interfaces::SetFloatRequest_<ContainerAllocator1> & lhs, const ::ainex_interfaces::SetFloatRequest_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ainex_interfaces::SetFloatRequest_<ContainerAllocator1> & lhs, const ::ainex_interfaces::SetFloatRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ainex_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ainex_interfaces::SetFloatRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainex_interfaces::SetFloatRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainex_interfaces::SetFloatRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainex_interfaces::SetFloatRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainex_interfaces::SetFloatRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainex_interfaces::SetFloatRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ainex_interfaces::SetFloatRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fdb28210bfa9d7c91146260178d9a584";
  }

  static const char* value(const ::ainex_interfaces::SetFloatRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfdb28210bfa9d7c9ULL;
  static const uint64_t static_value2 = 0x1146260178d9a584ULL;
};

template<class ContainerAllocator>
struct DataType< ::ainex_interfaces::SetFloatRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ainex_interfaces/SetFloatRequest";
  }

  static const char* value(const ::ainex_interfaces::SetFloatRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ainex_interfaces::SetFloatRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 data\n"
;
  }

  static const char* value(const ::ainex_interfaces::SetFloatRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ainex_interfaces::SetFloatRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetFloatRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ainex_interfaces::SetFloatRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ainex_interfaces::SetFloatRequest_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<double>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AINEX_INTERFACES_MESSAGE_SETFLOATREQUEST_H
