// Generated by gencpp from file ainex_interfaces/SetFloat.msg
// DO NOT EDIT!


#ifndef AINEX_INTERFACES_MESSAGE_SETFLOAT_H
#define AINEX_INTERFACES_MESSAGE_SETFLOAT_H

#include <ros/service_traits.h>


#include <ainex_interfaces/SetFloatRequest.h>
#include <ainex_interfaces/SetFloatResponse.h>


namespace ainex_interfaces
{

struct SetFloat
{

typedef SetFloatRequest Request;
typedef SetFloatResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFloat
} // namespace ainex_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ainex_interfaces::SetFloat > {
  static const char* value()
  {
    return "3f47c51e9da05852f0d7f484f9279955";
  }

  static const char* value(const ::ainex_interfaces::SetFloat&) { return value(); }
};

template<>
struct DataType< ::ainex_interfaces::SetFloat > {
  static const char* value()
  {
    return "ainex_interfaces/SetFloat";
  }

  static const char* value(const ::ainex_interfaces::SetFloat&) { return value(); }
};


// service_traits::MD5Sum< ::ainex_interfaces::SetFloatRequest> should match
// service_traits::MD5Sum< ::ainex_interfaces::SetFloat >
template<>
struct MD5Sum< ::ainex_interfaces::SetFloatRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ainex_interfaces::SetFloat >::value();
  }
  static const char* value(const ::ainex_interfaces::SetFloatRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ainex_interfaces::SetFloatRequest> should match
// service_traits::DataType< ::ainex_interfaces::SetFloat >
template<>
struct DataType< ::ainex_interfaces::SetFloatRequest>
{
  static const char* value()
  {
    return DataType< ::ainex_interfaces::SetFloat >::value();
  }
  static const char* value(const ::ainex_interfaces::SetFloatRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ainex_interfaces::SetFloatResponse> should match
// service_traits::MD5Sum< ::ainex_interfaces::SetFloat >
template<>
struct MD5Sum< ::ainex_interfaces::SetFloatResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ainex_interfaces::SetFloat >::value();
  }
  static const char* value(const ::ainex_interfaces::SetFloatResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ainex_interfaces::SetFloatResponse> should match
// service_traits::DataType< ::ainex_interfaces::SetFloat >
template<>
struct DataType< ::ainex_interfaces::SetFloatResponse>
{
  static const char* value()
  {
    return DataType< ::ainex_interfaces::SetFloat >::value();
  }
  static const char* value(const ::ainex_interfaces::SetFloatResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AINEX_INTERFACES_MESSAGE_SETFLOAT_H
