// Generated by gencpp from file ainex_interfaces/SetPoint.msg
// DO NOT EDIT!


#ifndef AINEX_INTERFACES_MESSAGE_SETPOINT_H
#define AINEX_INTERFACES_MESSAGE_SETPOINT_H

#include <ros/service_traits.h>


#include <ainex_interfaces/SetPointRequest.h>
#include <ainex_interfaces/SetPointResponse.h>


namespace ainex_interfaces
{

struct SetPoint
{

typedef SetPointRequest Request;
typedef SetPointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPoint
} // namespace ainex_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ainex_interfaces::SetPoint > {
  static const char* value()
  {
    return "efb349b09ac9e0d4c8ef08d9ad9508b4";
  }

  static const char* value(const ::ainex_interfaces::SetPoint&) { return value(); }
};

template<>
struct DataType< ::ainex_interfaces::SetPoint > {
  static const char* value()
  {
    return "ainex_interfaces/SetPoint";
  }

  static const char* value(const ::ainex_interfaces::SetPoint&) { return value(); }
};


// service_traits::MD5Sum< ::ainex_interfaces::SetPointRequest> should match
// service_traits::MD5Sum< ::ainex_interfaces::SetPoint >
template<>
struct MD5Sum< ::ainex_interfaces::SetPointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ainex_interfaces::SetPoint >::value();
  }
  static const char* value(const ::ainex_interfaces::SetPointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ainex_interfaces::SetPointRequest> should match
// service_traits::DataType< ::ainex_interfaces::SetPoint >
template<>
struct DataType< ::ainex_interfaces::SetPointRequest>
{
  static const char* value()
  {
    return DataType< ::ainex_interfaces::SetPoint >::value();
  }
  static const char* value(const ::ainex_interfaces::SetPointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ainex_interfaces::SetPointResponse> should match
// service_traits::MD5Sum< ::ainex_interfaces::SetPoint >
template<>
struct MD5Sum< ::ainex_interfaces::SetPointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ainex_interfaces::SetPoint >::value();
  }
  static const char* value(const ::ainex_interfaces::SetPointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ainex_interfaces::SetPointResponse> should match
// service_traits::DataType< ::ainex_interfaces::SetPoint >
template<>
struct DataType< ::ainex_interfaces::SetPointResponse>
{
  static const char* value()
  {
    return DataType< ::ainex_interfaces::SetPoint >::value();
  }
  static const char* value(const ::ainex_interfaces::SetPointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AINEX_INTERFACES_MESSAGE_SETPOINT_H
