// Generated by gencpp from file ainex_interfaces/SetRGBRequest.msg
// DO NOT EDIT!


#ifndef AINEX_INTERFACES_MESSAGE_SETRGBREQUEST_H
#define AINEX_INTERFACES_MESSAGE_SETRGBREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ainex_interfaces/RGB.h>

namespace ainex_interfaces
{
template <class ContainerAllocator>
struct SetRGBRequest_
{
  typedef SetRGBRequest_<ContainerAllocator> Type;

  SetRGBRequest_()
    : data()  {
    }
  SetRGBRequest_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::ainex_interfaces::RGB_<ContainerAllocator>  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::ainex_interfaces::SetRGBRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ainex_interfaces::SetRGBRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetRGBRequest_

typedef ::ainex_interfaces::SetRGBRequest_<std::allocator<void> > SetRGBRequest;

typedef boost::shared_ptr< ::ainex_interfaces::SetRGBRequest > SetRGBRequestPtr;
typedef boost::shared_ptr< ::ainex_interfaces::SetRGBRequest const> SetRGBRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ainex_interfaces::SetRGBRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ainex_interfaces::SetRGBRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ainex_interfaces::SetRGBRequest_<ContainerAllocator1> & lhs, const ::ainex_interfaces::SetRGBRequest_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ainex_interfaces::SetRGBRequest_<ContainerAllocator1> & lhs, const ::ainex_interfaces::SetRGBRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ainex_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ainex_interfaces::SetRGBRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainex_interfaces::SetRGBRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainex_interfaces::SetRGBRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainex_interfaces::SetRGBRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainex_interfaces::SetRGBRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainex_interfaces::SetRGBRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ainex_interfaces::SetRGBRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6623ad4c1a4ce93278b9731d5879e672";
  }

  static const char* value(const ::ainex_interfaces::SetRGBRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6623ad4c1a4ce932ULL;
  static const uint64_t static_value2 = 0x78b9731d5879e672ULL;
};

template<class ContainerAllocator>
struct DataType< ::ainex_interfaces::SetRGBRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ainex_interfaces/SetRGBRequest";
  }

  static const char* value(const ::ainex_interfaces::SetRGBRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ainex_interfaces::SetRGBRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ainex_interfaces/RGB data\n"
"\n"
"================================================================================\n"
"MSG: ainex_interfaces/RGB\n"
"int16 r\n"
"int16 g\n"
"int16 b\n"
;
  }

  static const char* value(const ::ainex_interfaces::SetRGBRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ainex_interfaces::SetRGBRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetRGBRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ainex_interfaces::SetRGBRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ainex_interfaces::SetRGBRequest_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    s << std::endl;
    Printer< ::ainex_interfaces::RGB_<ContainerAllocator> >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AINEX_INTERFACES_MESSAGE_SETRGBREQUEST_H
