// Generated by gencpp from file ainex_interfaces/SetRGB.msg
// DO NOT EDIT!


#ifndef AINEX_INTERFACES_MESSAGE_SETRGB_H
#define AINEX_INTERFACES_MESSAGE_SETRGB_H

#include <ros/service_traits.h>


#include <ainex_interfaces/SetRGBRequest.h>
#include <ainex_interfaces/SetRGBResponse.h>


namespace ainex_interfaces
{

struct SetRGB
{

typedef SetRGBRequest Request;
typedef SetRGBResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetRGB
} // namespace ainex_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ainex_interfaces::SetRGB > {
  static const char* value()
  {
    return "0651eef3b42b0598c5024b059bb8dabe";
  }

  static const char* value(const ::ainex_interfaces::SetRGB&) { return value(); }
};

template<>
struct DataType< ::ainex_interfaces::SetRGB > {
  static const char* value()
  {
    return "ainex_interfaces/SetRGB";
  }

  static const char* value(const ::ainex_interfaces::SetRGB&) { return value(); }
};


// service_traits::MD5Sum< ::ainex_interfaces::SetRGBRequest> should match
// service_traits::MD5Sum< ::ainex_interfaces::SetRGB >
template<>
struct MD5Sum< ::ainex_interfaces::SetRGBRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ainex_interfaces::SetRGB >::value();
  }
  static const char* value(const ::ainex_interfaces::SetRGBRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ainex_interfaces::SetRGBRequest> should match
// service_traits::DataType< ::ainex_interfaces::SetRGB >
template<>
struct DataType< ::ainex_interfaces::SetRGBRequest>
{
  static const char* value()
  {
    return DataType< ::ainex_interfaces::SetRGB >::value();
  }
  static const char* value(const ::ainex_interfaces::SetRGBRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ainex_interfaces::SetRGBResponse> should match
// service_traits::MD5Sum< ::ainex_interfaces::SetRGB >
template<>
struct MD5Sum< ::ainex_interfaces::SetRGBResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ainex_interfaces::SetRGB >::value();
  }
  static const char* value(const ::ainex_interfaces::SetRGBResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ainex_interfaces::SetRGBResponse> should match
// service_traits::DataType< ::ainex_interfaces::SetRGB >
template<>
struct DataType< ::ainex_interfaces::SetRGBResponse>
{
  static const char* value()
  {
    return DataType< ::ainex_interfaces::SetRGB >::value();
  }
  static const char* value(const ::ainex_interfaces::SetRGBResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AINEX_INTERFACES_MESSAGE_SETRGB_H
