// Generated by gencpp from file ainex_interfaces/SetString.msg
// DO NOT EDIT!


#ifndef AINEX_INTERFACES_MESSAGE_SETSTRING_H
#define AINEX_INTERFACES_MESSAGE_SETSTRING_H

#include <ros/service_traits.h>


#include <ainex_interfaces/SetStringRequest.h>
#include <ainex_interfaces/SetStringResponse.h>


namespace ainex_interfaces
{

struct SetString
{

typedef SetStringRequest Request;
typedef SetStringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetString
} // namespace ainex_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ainex_interfaces::SetString > {
  static const char* value()
  {
    return "546971982e3fbbd5a41e60fb6432e357";
  }

  static const char* value(const ::ainex_interfaces::SetString&) { return value(); }
};

template<>
struct DataType< ::ainex_interfaces::SetString > {
  static const char* value()
  {
    return "ainex_interfaces/SetString";
  }

  static const char* value(const ::ainex_interfaces::SetString&) { return value(); }
};


// service_traits::MD5Sum< ::ainex_interfaces::SetStringRequest> should match
// service_traits::MD5Sum< ::ainex_interfaces::SetString >
template<>
struct MD5Sum< ::ainex_interfaces::SetStringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ainex_interfaces::SetString >::value();
  }
  static const char* value(const ::ainex_interfaces::SetStringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ainex_interfaces::SetStringRequest> should match
// service_traits::DataType< ::ainex_interfaces::SetString >
template<>
struct DataType< ::ainex_interfaces::SetStringRequest>
{
  static const char* value()
  {
    return DataType< ::ainex_interfaces::SetString >::value();
  }
  static const char* value(const ::ainex_interfaces::SetStringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ainex_interfaces::SetStringResponse> should match
// service_traits::MD5Sum< ::ainex_interfaces::SetString >
template<>
struct MD5Sum< ::ainex_interfaces::SetStringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ainex_interfaces::SetString >::value();
  }
  static const char* value(const ::ainex_interfaces::SetStringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ainex_interfaces::SetStringResponse> should match
// service_traits::DataType< ::ainex_interfaces::SetString >
template<>
struct DataType< ::ainex_interfaces::SetStringResponse>
{
  static const char* value()
  {
    return DataType< ::ainex_interfaces::SetString >::value();
  }
  static const char* value(const ::ainex_interfaces::SetStringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AINEX_INTERFACES_MESSAGE_SETSTRING_H
