// Generated by gencpp from file ainex_interfaces/SetWalkingCommand.msg
// DO NOT EDIT!


#ifndef AINEX_INTERFACES_MESSAGE_SETWALKINGCOMMAND_H
#define AINEX_INTERFACES_MESSAGE_SETWALKINGCOMMAND_H

#include <ros/service_traits.h>


#include <ainex_interfaces/SetWalkingCommandRequest.h>
#include <ainex_interfaces/SetWalkingCommandResponse.h>


namespace ainex_interfaces
{

struct SetWalkingCommand
{

typedef SetWalkingCommandRequest Request;
typedef SetWalkingCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetWalkingCommand
} // namespace ainex_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ainex_interfaces::SetWalkingCommand > {
  static const char* value()
  {
    return "2fb3aa2736d70ecbfc297d3d9b879661";
  }

  static const char* value(const ::ainex_interfaces::SetWalkingCommand&) { return value(); }
};

template<>
struct DataType< ::ainex_interfaces::SetWalkingCommand > {
  static const char* value()
  {
    return "ainex_interfaces/SetWalkingCommand";
  }

  static const char* value(const ::ainex_interfaces::SetWalkingCommand&) { return value(); }
};


// service_traits::MD5Sum< ::ainex_interfaces::SetWalkingCommandRequest> should match
// service_traits::MD5Sum< ::ainex_interfaces::SetWalkingCommand >
template<>
struct MD5Sum< ::ainex_interfaces::SetWalkingCommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ainex_interfaces::SetWalkingCommand >::value();
  }
  static const char* value(const ::ainex_interfaces::SetWalkingCommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ainex_interfaces::SetWalkingCommandRequest> should match
// service_traits::DataType< ::ainex_interfaces::SetWalkingCommand >
template<>
struct DataType< ::ainex_interfaces::SetWalkingCommandRequest>
{
  static const char* value()
  {
    return DataType< ::ainex_interfaces::SetWalkingCommand >::value();
  }
  static const char* value(const ::ainex_interfaces::SetWalkingCommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ainex_interfaces::SetWalkingCommandResponse> should match
// service_traits::MD5Sum< ::ainex_interfaces::SetWalkingCommand >
template<>
struct MD5Sum< ::ainex_interfaces::SetWalkingCommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ainex_interfaces::SetWalkingCommand >::value();
  }
  static const char* value(const ::ainex_interfaces::SetWalkingCommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ainex_interfaces::SetWalkingCommandResponse> should match
// service_traits::DataType< ::ainex_interfaces::SetWalkingCommand >
template<>
struct DataType< ::ainex_interfaces::SetWalkingCommandResponse>
{
  static const char* value()
  {
    return DataType< ::ainex_interfaces::SetWalkingCommand >::value();
  }
  static const char* value(const ::ainex_interfaces::SetWalkingCommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AINEX_INTERFACES_MESSAGE_SETWALKINGCOMMAND_H
