// Generated by gencpp from file ainex_interfaces/SetWalkingParam.msg
// DO NOT EDIT!


#ifndef AINEX_INTERFACES_MESSAGE_SETWALKINGPARAM_H
#define AINEX_INTERFACES_MESSAGE_SETWALKINGPARAM_H

#include <ros/service_traits.h>


#include <ainex_interfaces/SetWalkingParamRequest.h>
#include <ainex_interfaces/SetWalkingParamResponse.h>


namespace ainex_interfaces
{

struct SetWalkingParam
{

typedef SetWalkingParamRequest Request;
typedef SetWalkingParamResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetWalkingParam
} // namespace ainex_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ainex_interfaces::SetWalkingParam > {
  static const char* value()
  {
    return "029b54a504db3afb97699271da6b28e2";
  }

  static const char* value(const ::ainex_interfaces::SetWalkingParam&) { return value(); }
};

template<>
struct DataType< ::ainex_interfaces::SetWalkingParam > {
  static const char* value()
  {
    return "ainex_interfaces/SetWalkingParam";
  }

  static const char* value(const ::ainex_interfaces::SetWalkingParam&) { return value(); }
};


// service_traits::MD5Sum< ::ainex_interfaces::SetWalkingParamRequest> should match
// service_traits::MD5Sum< ::ainex_interfaces::SetWalkingParam >
template<>
struct MD5Sum< ::ainex_interfaces::SetWalkingParamRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ainex_interfaces::SetWalkingParam >::value();
  }
  static const char* value(const ::ainex_interfaces::SetWalkingParamRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ainex_interfaces::SetWalkingParamRequest> should match
// service_traits::DataType< ::ainex_interfaces::SetWalkingParam >
template<>
struct DataType< ::ainex_interfaces::SetWalkingParamRequest>
{
  static const char* value()
  {
    return DataType< ::ainex_interfaces::SetWalkingParam >::value();
  }
  static const char* value(const ::ainex_interfaces::SetWalkingParamRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ainex_interfaces::SetWalkingParamResponse> should match
// service_traits::MD5Sum< ::ainex_interfaces::SetWalkingParam >
template<>
struct MD5Sum< ::ainex_interfaces::SetWalkingParamResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ainex_interfaces::SetWalkingParam >::value();
  }
  static const char* value(const ::ainex_interfaces::SetWalkingParamResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ainex_interfaces::SetWalkingParamResponse> should match
// service_traits::DataType< ::ainex_interfaces::SetWalkingParam >
template<>
struct DataType< ::ainex_interfaces::SetWalkingParamResponse>
{
  static const char* value()
  {
    return DataType< ::ainex_interfaces::SetWalkingParam >::value();
  }
  static const char* value(const ::ainex_interfaces::SetWalkingParamResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AINEX_INTERFACES_MESSAGE_SETWALKINGPARAM_H
