// Generated by gencpp from file ainex_interfaces/SetWalkingParamResponse.msg
// DO NOT EDIT!


#ifndef AINEX_INTERFACES_MESSAGE_SETWALKINGPARAMRESPONSE_H
#define AINEX_INTERFACES_MESSAGE_SETWALKINGPARAMRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ainex_interfaces
{
template <class ContainerAllocator>
struct SetWalkingParamResponse_
{
  typedef SetWalkingParamResponse_<ContainerAllocator> Type;

  SetWalkingParamResponse_()
    : result(false)  {
    }
  SetWalkingParamResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::ainex_interfaces::SetWalkingParamResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ainex_interfaces::SetWalkingParamResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetWalkingParamResponse_

typedef ::ainex_interfaces::SetWalkingParamResponse_<std::allocator<void> > SetWalkingParamResponse;

typedef boost::shared_ptr< ::ainex_interfaces::SetWalkingParamResponse > SetWalkingParamResponsePtr;
typedef boost::shared_ptr< ::ainex_interfaces::SetWalkingParamResponse const> SetWalkingParamResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ainex_interfaces::SetWalkingParamResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ainex_interfaces::SetWalkingParamResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ainex_interfaces::SetWalkingParamResponse_<ContainerAllocator1> & lhs, const ::ainex_interfaces::SetWalkingParamResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ainex_interfaces::SetWalkingParamResponse_<ContainerAllocator1> & lhs, const ::ainex_interfaces::SetWalkingParamResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ainex_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ainex_interfaces::SetWalkingParamResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainex_interfaces::SetWalkingParamResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainex_interfaces::SetWalkingParamResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainex_interfaces::SetWalkingParamResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainex_interfaces::SetWalkingParamResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainex_interfaces::SetWalkingParamResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ainex_interfaces::SetWalkingParamResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::ainex_interfaces::SetWalkingParamResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::ainex_interfaces::SetWalkingParamResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ainex_interfaces/SetWalkingParamResponse";
  }

  static const char* value(const ::ainex_interfaces::SetWalkingParamResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ainex_interfaces::SetWalkingParamResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool            result\n"
;
  }

  static const char* value(const ::ainex_interfaces::SetWalkingParamResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ainex_interfaces::SetWalkingParamResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetWalkingParamResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ainex_interfaces::SetWalkingParamResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ainex_interfaces::SetWalkingParamResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AINEX_INTERFACES_MESSAGE_SETWALKINGPARAMRESPONSE_H
