// Generated by gencpp from file ainex_interfaces/SetWalkingCommandRequest.msg
// DO NOT EDIT!


#ifndef AINEX_INTERFACES_MESSAGE_SETWALKINGCOMMANDREQUEST_H
#define AINEX_INTERFACES_MESSAGE_SETWALKINGCOMMANDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ainex_interfaces
{
template <class ContainerAllocator>
struct SetWalkingCommandRequest_
{
  typedef SetWalkingCommandRequest_<ContainerAllocator> Type;

  SetWalkingCommandRequest_()
    : command()  {
    }
  SetWalkingCommandRequest_(const ContainerAllocator& _alloc)
    : command(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::ainex_interfaces::SetWalkingCommandRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ainex_interfaces::SetWalkingCommandRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetWalkingCommandRequest_

typedef ::ainex_interfaces::SetWalkingCommandRequest_<std::allocator<void> > SetWalkingCommandRequest;

typedef boost::shared_ptr< ::ainex_interfaces::SetWalkingCommandRequest > SetWalkingCommandRequestPtr;
typedef boost::shared_ptr< ::ainex_interfaces::SetWalkingCommandRequest const> SetWalkingCommandRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ainex_interfaces::SetWalkingCommandRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ainex_interfaces::SetWalkingCommandRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ainex_interfaces::SetWalkingCommandRequest_<ContainerAllocator1> & lhs, const ::ainex_interfaces::SetWalkingCommandRequest_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ainex_interfaces::SetWalkingCommandRequest_<ContainerAllocator1> & lhs, const ::ainex_interfaces::SetWalkingCommandRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ainex_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ainex_interfaces::SetWalkingCommandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainex_interfaces::SetWalkingCommandRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainex_interfaces::SetWalkingCommandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainex_interfaces::SetWalkingCommandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainex_interfaces::SetWalkingCommandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainex_interfaces::SetWalkingCommandRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ainex_interfaces::SetWalkingCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cba5e21e920a3a2b7b375cb65b64cdea";
  }

  static const char* value(const ::ainex_interfaces::SetWalkingCommandRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcba5e21e920a3a2bULL;
  static const uint64_t static_value2 = 0x7b375cb65b64cdeaULL;
};

template<class ContainerAllocator>
struct DataType< ::ainex_interfaces::SetWalkingCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ainex_interfaces/SetWalkingCommandRequest";
  }

  static const char* value(const ::ainex_interfaces::SetWalkingCommandRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ainex_interfaces::SetWalkingCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string    command\n"
;
  }

  static const char* value(const ::ainex_interfaces::SetWalkingCommandRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ainex_interfaces::SetWalkingCommandRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetWalkingCommandRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ainex_interfaces::SetWalkingCommandRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ainex_interfaces::SetWalkingCommandRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AINEX_INTERFACES_MESSAGE_SETWALKINGCOMMANDREQUEST_H
