(cl:in-package ainex_interfaces-msg)
(cl:export '(INIT_X_OFFSET-VAL
          INIT_X_OFFSET
          INIT_Y_OFFSET-VAL
          INIT_Y_OFFSET
          INIT_Z_OFFSET-VAL
          INIT_Z_OFFSET
          INIT_ROLL_OFFSET-VAL
          INIT_ROLL_OFFSET
          INIT_PITCH_OFFSET-VAL
          INIT_PITCH_OFFSET
          INIT_YAW_OFFSET-VAL
          INIT_YAW_OFFSET
          PERIOD_TIME-VAL
          PERIOD_TIME
          DSP_RATIO-VAL
          DSP_RATIO
          STEP_FB_RATIO-VAL
          STEP_FB_RATIO
          PERIOD_TIMES-VAL
          PERIOD_TIMES
          X_MOVE_AMPLITUDE-VAL
          X_MOVE_AMPLITUDE
          Y_MOVE_AMPLITUDE-VAL
          Y_MOVE_AMPLITUDE
          Z_MOVE_AMPLITUDE-VAL
          Z_MOVE_AMPLITUDE
          ANGLE_MOVE_AMPLITUDE-VAL
          ANGLE_MOVE_AMPLITUDE
          MOVE_AIM_ON-VAL
          MOVE_AIM_ON
          ARM_SWING_GAIN-VAL
          ARM_SWING_GAIN
          Y_SWAP_AMPLITUDE-VAL
          Y_SWAP_AMPLITUDE
          Z_SWAP_AMPLITUDE-VAL
          Z_SWAP_AMPLITUDE
          PELVIS_OFFSET-VAL
          PELVIS_OFFSET
          HIP_PITCH_OFFSET-VAL
          HIP_PITCH_OFFSET
))