# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ainex_interfaces/ColorsDetect.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import ainex_interfaces.msg

class ColorsDetect(genpy.Message):
  _md5sum = "e8024ffa57fcf070b87e6db34ea1620a"
  _type = "ainex_interfaces/ColorsDetect"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """ainex_interfaces/ColorDetect[] data

================================================================================
MSG: ainex_interfaces/ColorDetect
string color_name
bool use_name
string detect_type
ainex_interfaces/ROI roi
ainex_interfaces/LineROI line_roi
uint32[] image_process_size
int16[] lab_min
int16[] lab_max
float64 min_area
float64 max_area

================================================================================
MSG: ainex_interfaces/ROI
int32 y_min
int32 y_max
int32 x_min
int32 x_max

================================================================================
MSG: ainex_interfaces/LineROI
ainex_interfaces/ROI up
ainex_interfaces/ROI center
ainex_interfaces/ROI down
"""
  __slots__ = ['data']
  _slot_types = ['ainex_interfaces/ColorDetect[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       data

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ColorsDetect, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.data is None:
        self.data = []
    else:
      self.data = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.data)
      buff.write(_struct_I.pack(length))
      for val1 in self.data:
        _x = val1.color_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.use_name
        buff.write(_get_struct_B().pack(_x))
        _x = val1.detect_type
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v1 = val1.roi
        _x = _v1
        buff.write(_get_struct_4i().pack(_x.y_min, _x.y_max, _x.x_min, _x.x_max))
        _v2 = val1.line_roi
        _v3 = _v2.up
        _x = _v3
        buff.write(_get_struct_4i().pack(_x.y_min, _x.y_max, _x.x_min, _x.x_max))
        _v4 = _v2.center
        _x = _v4
        buff.write(_get_struct_4i().pack(_x.y_min, _x.y_max, _x.x_min, _x.x_max))
        _v5 = _v2.down
        _x = _v5
        buff.write(_get_struct_4i().pack(_x.y_min, _x.y_max, _x.x_min, _x.x_max))
        length = len(val1.image_process_size)
        buff.write(_struct_I.pack(length))
        pattern = '<%sI'%length
        buff.write(struct.Struct(pattern).pack(*val1.image_process_size))
        length = len(val1.lab_min)
        buff.write(_struct_I.pack(length))
        pattern = '<%sh'%length
        buff.write(struct.Struct(pattern).pack(*val1.lab_min))
        length = len(val1.lab_max)
        buff.write(_struct_I.pack(length))
        pattern = '<%sh'%length
        buff.write(struct.Struct(pattern).pack(*val1.lab_max))
        _x = val1
        buff.write(_get_struct_2d().pack(_x.min_area, _x.max_area))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.data is None:
        self.data = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.data = []
      for i in range(0, length):
        val1 = ainex_interfaces.msg.ColorDetect()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.color_name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.color_name = str[start:end]
        start = end
        end += 1
        (val1.use_name,) = _get_struct_B().unpack(str[start:end])
        val1.use_name = bool(val1.use_name)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.detect_type = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.detect_type = str[start:end]
        _v6 = val1.roi
        _x = _v6
        start = end
        end += 16
        (_x.y_min, _x.y_max, _x.x_min, _x.x_max,) = _get_struct_4i().unpack(str[start:end])
        _v7 = val1.line_roi
        _v8 = _v7.up
        _x = _v8
        start = end
        end += 16
        (_x.y_min, _x.y_max, _x.x_min, _x.x_max,) = _get_struct_4i().unpack(str[start:end])
        _v9 = _v7.center
        _x = _v9
        start = end
        end += 16
        (_x.y_min, _x.y_max, _x.x_min, _x.x_max,) = _get_struct_4i().unpack(str[start:end])
        _v10 = _v7.down
        _x = _v10
        start = end
        end += 16
        (_x.y_min, _x.y_max, _x.x_min, _x.x_max,) = _get_struct_4i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sI'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.image_process_size = s.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sh'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.lab_min = s.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sh'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.lab_max = s.unpack(str[start:end])
        _x = val1
        start = end
        end += 16
        (_x.min_area, _x.max_area,) = _get_struct_2d().unpack(str[start:end])
        self.data.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.data)
      buff.write(_struct_I.pack(length))
      for val1 in self.data:
        _x = val1.color_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.use_name
        buff.write(_get_struct_B().pack(_x))
        _x = val1.detect_type
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v11 = val1.roi
        _x = _v11
        buff.write(_get_struct_4i().pack(_x.y_min, _x.y_max, _x.x_min, _x.x_max))
        _v12 = val1.line_roi
        _v13 = _v12.up
        _x = _v13
        buff.write(_get_struct_4i().pack(_x.y_min, _x.y_max, _x.x_min, _x.x_max))
        _v14 = _v12.center
        _x = _v14
        buff.write(_get_struct_4i().pack(_x.y_min, _x.y_max, _x.x_min, _x.x_max))
        _v15 = _v12.down
        _x = _v15
        buff.write(_get_struct_4i().pack(_x.y_min, _x.y_max, _x.x_min, _x.x_max))
        length = len(val1.image_process_size)
        buff.write(_struct_I.pack(length))
        pattern = '<%sI'%length
        buff.write(val1.image_process_size.tostring())
        length = len(val1.lab_min)
        buff.write(_struct_I.pack(length))
        pattern = '<%sh'%length
        buff.write(val1.lab_min.tostring())
        length = len(val1.lab_max)
        buff.write(_struct_I.pack(length))
        pattern = '<%sh'%length
        buff.write(val1.lab_max.tostring())
        _x = val1
        buff.write(_get_struct_2d().pack(_x.min_area, _x.max_area))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.data is None:
        self.data = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.data = []
      for i in range(0, length):
        val1 = ainex_interfaces.msg.ColorDetect()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.color_name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.color_name = str[start:end]
        start = end
        end += 1
        (val1.use_name,) = _get_struct_B().unpack(str[start:end])
        val1.use_name = bool(val1.use_name)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.detect_type = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.detect_type = str[start:end]
        _v16 = val1.roi
        _x = _v16
        start = end
        end += 16
        (_x.y_min, _x.y_max, _x.x_min, _x.x_max,) = _get_struct_4i().unpack(str[start:end])
        _v17 = val1.line_roi
        _v18 = _v17.up
        _x = _v18
        start = end
        end += 16
        (_x.y_min, _x.y_max, _x.x_min, _x.x_max,) = _get_struct_4i().unpack(str[start:end])
        _v19 = _v17.center
        _x = _v19
        start = end
        end += 16
        (_x.y_min, _x.y_max, _x.x_min, _x.x_max,) = _get_struct_4i().unpack(str[start:end])
        _v20 = _v17.down
        _x = _v20
        start = end
        end += 16
        (_x.y_min, _x.y_max, _x.x_min, _x.x_max,) = _get_struct_4i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sI'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.image_process_size = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=length)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sh'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.lab_min = numpy.frombuffer(str[start:end], dtype=numpy.int16, count=length)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sh'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.lab_max = numpy.frombuffer(str[start:end], dtype=numpy.int16, count=length)
        _x = val1
        start = end
        end += 16
        (_x.min_area, _x.max_area,) = _get_struct_2d().unpack(str[start:end])
        self.data.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2d = None
def _get_struct_2d():
    global _struct_2d
    if _struct_2d is None:
        _struct_2d = struct.Struct("<2d")
    return _struct_2d
_struct_4i = None
def _get_struct_4i():
    global _struct_4i
    if _struct_4i is None:
        _struct_4i = struct.Struct("<4i")
    return _struct_4i
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
