# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ainex_interfaces/ColorDetect.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import ainex_interfaces.msg

class ColorDetect(genpy.Message):
  _md5sum = "7c6d76275e561b8430ce7facd08f9909"
  _type = "ainex_interfaces/ColorDetect"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string color_name
bool use_name
string detect_type
ainex_interfaces/ROI roi
ainex_interfaces/LineROI line_roi
uint32[] image_process_size
int16[] lab_min
int16[] lab_max
float64 min_area
float64 max_area

================================================================================
MSG: ainex_interfaces/ROI
int32 y_min
int32 y_max
int32 x_min
int32 x_max

================================================================================
MSG: ainex_interfaces/LineROI
ainex_interfaces/ROI up
ainex_interfaces/ROI center
ainex_interfaces/ROI down
"""
  __slots__ = ['color_name','use_name','detect_type','roi','line_roi','image_process_size','lab_min','lab_max','min_area','max_area']
  _slot_types = ['string','bool','string','ainex_interfaces/ROI','ainex_interfaces/LineROI','uint32[]','int16[]','int16[]','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       color_name,use_name,detect_type,roi,line_roi,image_process_size,lab_min,lab_max,min_area,max_area

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ColorDetect, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.color_name is None:
        self.color_name = ''
      if self.use_name is None:
        self.use_name = False
      if self.detect_type is None:
        self.detect_type = ''
      if self.roi is None:
        self.roi = ainex_interfaces.msg.ROI()
      if self.line_roi is None:
        self.line_roi = ainex_interfaces.msg.LineROI()
      if self.image_process_size is None:
        self.image_process_size = []
      if self.lab_min is None:
        self.lab_min = []
      if self.lab_max is None:
        self.lab_max = []
      if self.min_area is None:
        self.min_area = 0.
      if self.max_area is None:
        self.max_area = 0.
    else:
      self.color_name = ''
      self.use_name = False
      self.detect_type = ''
      self.roi = ainex_interfaces.msg.ROI()
      self.line_roi = ainex_interfaces.msg.LineROI()
      self.image_process_size = []
      self.lab_min = []
      self.lab_max = []
      self.min_area = 0.
      self.max_area = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.color_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.use_name
      buff.write(_get_struct_B().pack(_x))
      _x = self.detect_type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_16i().pack(_x.roi.y_min, _x.roi.y_max, _x.roi.x_min, _x.roi.x_max, _x.line_roi.up.y_min, _x.line_roi.up.y_max, _x.line_roi.up.x_min, _x.line_roi.up.x_max, _x.line_roi.center.y_min, _x.line_roi.center.y_max, _x.line_roi.center.x_min, _x.line_roi.center.x_max, _x.line_roi.down.y_min, _x.line_roi.down.y_max, _x.line_roi.down.x_min, _x.line_roi.down.x_max))
      length = len(self.image_process_size)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(struct.Struct(pattern).pack(*self.image_process_size))
      length = len(self.lab_min)
      buff.write(_struct_I.pack(length))
      pattern = '<%sh'%length
      buff.write(struct.Struct(pattern).pack(*self.lab_min))
      length = len(self.lab_max)
      buff.write(_struct_I.pack(length))
      pattern = '<%sh'%length
      buff.write(struct.Struct(pattern).pack(*self.lab_max))
      _x = self
      buff.write(_get_struct_2d().pack(_x.min_area, _x.max_area))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.roi is None:
        self.roi = ainex_interfaces.msg.ROI()
      if self.line_roi is None:
        self.line_roi = ainex_interfaces.msg.LineROI()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.color_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.color_name = str[start:end]
      start = end
      end += 1
      (self.use_name,) = _get_struct_B().unpack(str[start:end])
      self.use_name = bool(self.use_name)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.detect_type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.detect_type = str[start:end]
      _x = self
      start = end
      end += 64
      (_x.roi.y_min, _x.roi.y_max, _x.roi.x_min, _x.roi.x_max, _x.line_roi.up.y_min, _x.line_roi.up.y_max, _x.line_roi.up.x_min, _x.line_roi.up.x_max, _x.line_roi.center.y_min, _x.line_roi.center.y_max, _x.line_roi.center.x_min, _x.line_roi.center.x_max, _x.line_roi.down.y_min, _x.line_roi.down.y_max, _x.line_roi.down.x_min, _x.line_roi.down.x_max,) = _get_struct_16i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.image_process_size = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sh'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.lab_min = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sh'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.lab_max = s.unpack(str[start:end])
      _x = self
      start = end
      end += 16
      (_x.min_area, _x.max_area,) = _get_struct_2d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.color_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.use_name
      buff.write(_get_struct_B().pack(_x))
      _x = self.detect_type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_16i().pack(_x.roi.y_min, _x.roi.y_max, _x.roi.x_min, _x.roi.x_max, _x.line_roi.up.y_min, _x.line_roi.up.y_max, _x.line_roi.up.x_min, _x.line_roi.up.x_max, _x.line_roi.center.y_min, _x.line_roi.center.y_max, _x.line_roi.center.x_min, _x.line_roi.center.x_max, _x.line_roi.down.y_min, _x.line_roi.down.y_max, _x.line_roi.down.x_min, _x.line_roi.down.x_max))
      length = len(self.image_process_size)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(self.image_process_size.tostring())
      length = len(self.lab_min)
      buff.write(_struct_I.pack(length))
      pattern = '<%sh'%length
      buff.write(self.lab_min.tostring())
      length = len(self.lab_max)
      buff.write(_struct_I.pack(length))
      pattern = '<%sh'%length
      buff.write(self.lab_max.tostring())
      _x = self
      buff.write(_get_struct_2d().pack(_x.min_area, _x.max_area))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.roi is None:
        self.roi = ainex_interfaces.msg.ROI()
      if self.line_roi is None:
        self.line_roi = ainex_interfaces.msg.LineROI()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.color_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.color_name = str[start:end]
      start = end
      end += 1
      (self.use_name,) = _get_struct_B().unpack(str[start:end])
      self.use_name = bool(self.use_name)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.detect_type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.detect_type = str[start:end]
      _x = self
      start = end
      end += 64
      (_x.roi.y_min, _x.roi.y_max, _x.roi.x_min, _x.roi.x_max, _x.line_roi.up.y_min, _x.line_roi.up.y_max, _x.line_roi.up.x_min, _x.line_roi.up.x_max, _x.line_roi.center.y_min, _x.line_roi.center.y_max, _x.line_roi.center.x_min, _x.line_roi.center.x_max, _x.line_roi.down.y_min, _x.line_roi.down.y_max, _x.line_roi.down.x_min, _x.line_roi.down.x_max,) = _get_struct_16i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.image_process_size = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sh'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.lab_min = numpy.frombuffer(str[start:end], dtype=numpy.int16, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sh'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.lab_max = numpy.frombuffer(str[start:end], dtype=numpy.int16, count=length)
      _x = self
      start = end
      end += 16
      (_x.min_area, _x.max_area,) = _get_struct_2d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_16i = None
def _get_struct_16i():
    global _struct_16i
    if _struct_16i is None:
        _struct_16i = struct.Struct("<16i")
    return _struct_16i
_struct_2d = None
def _get_struct_2d():
    global _struct_2d
    if _struct_2d is None:
        _struct_2d = struct.Struct("<2d")
    return _struct_2d
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
