# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ainex_interfaces/LineROI.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import ainex_interfaces.msg

class LineROI(genpy.Message):
  _md5sum = "bccdc6e8e70cb622e1827d4df83b58fa"
  _type = "ainex_interfaces/LineROI"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """ainex_interfaces/ROI up
ainex_interfaces/ROI center
ainex_interfaces/ROI down

================================================================================
MSG: ainex_interfaces/ROI
int32 y_min
int32 y_max
int32 x_min
int32 x_max
"""
  __slots__ = ['up','center','down']
  _slot_types = ['ainex_interfaces/ROI','ainex_interfaces/ROI','ainex_interfaces/ROI']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       up,center,down

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LineROI, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.up is None:
        self.up = ainex_interfaces.msg.ROI()
      if self.center is None:
        self.center = ainex_interfaces.msg.ROI()
      if self.down is None:
        self.down = ainex_interfaces.msg.ROI()
    else:
      self.up = ainex_interfaces.msg.ROI()
      self.center = ainex_interfaces.msg.ROI()
      self.down = ainex_interfaces.msg.ROI()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_12i().pack(_x.up.y_min, _x.up.y_max, _x.up.x_min, _x.up.x_max, _x.center.y_min, _x.center.y_max, _x.center.x_min, _x.center.x_max, _x.down.y_min, _x.down.y_max, _x.down.x_min, _x.down.x_max))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.up is None:
        self.up = ainex_interfaces.msg.ROI()
      if self.center is None:
        self.center = ainex_interfaces.msg.ROI()
      if self.down is None:
        self.down = ainex_interfaces.msg.ROI()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.up.y_min, _x.up.y_max, _x.up.x_min, _x.up.x_max, _x.center.y_min, _x.center.y_max, _x.center.x_min, _x.center.x_max, _x.down.y_min, _x.down.y_max, _x.down.x_min, _x.down.x_max,) = _get_struct_12i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_12i().pack(_x.up.y_min, _x.up.y_max, _x.up.x_min, _x.up.x_max, _x.center.y_min, _x.center.y_max, _x.center.x_min, _x.center.x_max, _x.down.y_min, _x.down.y_max, _x.down.x_min, _x.down.x_max))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.up is None:
        self.up = ainex_interfaces.msg.ROI()
      if self.center is None:
        self.center = ainex_interfaces.msg.ROI()
      if self.down is None:
        self.down = ainex_interfaces.msg.ROI()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.up.y_min, _x.up.y_max, _x.up.x_min, _x.up.x_max, _x.center.y_min, _x.center.y_max, _x.center.x_min, _x.center.x_max, _x.down.y_min, _x.down.y_max, _x.down.x_min, _x.down.x_max,) = _get_struct_12i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_12i = None
def _get_struct_12i():
    global _struct_12i
    if _struct_12i is None:
        _struct_12i = struct.Struct("<12i")
    return _struct_12i
