# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ainex_interfaces/WalkingParam.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class WalkingParam(genpy.Message):
  _md5sum = "33a0fc392acf75f9ca94c3da5d14814a"
  _type = "ainex_interfaces/WalkingParam"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """####### walking init pose #######
float32 init_x_offset
float32 init_y_offset
float32 init_z_offset
float32 init_roll_offset
float32 init_pitch_offset
float32 init_yaw_offset

####### time parameter #####
float32 period_time
float32 dsp_ratio
float32 step_fb_ratio
uint32 period_times

########## walking parameter ########
float32 x_move_amplitude
float32 y_move_amplitude
float32 z_move_amplitude
float32 angle_move_amplitude
bool move_aim_on
float32 arm_swing_gain
float32 y_swap_amplitude
float32 z_swap_amplitude
float32 pelvis_offset
float32 hip_pitch_offset
"""
  __slots__ = ['init_x_offset','init_y_offset','init_z_offset','init_roll_offset','init_pitch_offset','init_yaw_offset','period_time','dsp_ratio','step_fb_ratio','period_times','x_move_amplitude','y_move_amplitude','z_move_amplitude','angle_move_amplitude','move_aim_on','arm_swing_gain','y_swap_amplitude','z_swap_amplitude','pelvis_offset','hip_pitch_offset']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32','float32','float32','uint32','float32','float32','float32','float32','bool','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       init_x_offset,init_y_offset,init_z_offset,init_roll_offset,init_pitch_offset,init_yaw_offset,period_time,dsp_ratio,step_fb_ratio,period_times,x_move_amplitude,y_move_amplitude,z_move_amplitude,angle_move_amplitude,move_aim_on,arm_swing_gain,y_swap_amplitude,z_swap_amplitude,pelvis_offset,hip_pitch_offset

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(WalkingParam, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.init_x_offset is None:
        self.init_x_offset = 0.
      if self.init_y_offset is None:
        self.init_y_offset = 0.
      if self.init_z_offset is None:
        self.init_z_offset = 0.
      if self.init_roll_offset is None:
        self.init_roll_offset = 0.
      if self.init_pitch_offset is None:
        self.init_pitch_offset = 0.
      if self.init_yaw_offset is None:
        self.init_yaw_offset = 0.
      if self.period_time is None:
        self.period_time = 0.
      if self.dsp_ratio is None:
        self.dsp_ratio = 0.
      if self.step_fb_ratio is None:
        self.step_fb_ratio = 0.
      if self.period_times is None:
        self.period_times = 0
      if self.x_move_amplitude is None:
        self.x_move_amplitude = 0.
      if self.y_move_amplitude is None:
        self.y_move_amplitude = 0.
      if self.z_move_amplitude is None:
        self.z_move_amplitude = 0.
      if self.angle_move_amplitude is None:
        self.angle_move_amplitude = 0.
      if self.move_aim_on is None:
        self.move_aim_on = False
      if self.arm_swing_gain is None:
        self.arm_swing_gain = 0.
      if self.y_swap_amplitude is None:
        self.y_swap_amplitude = 0.
      if self.z_swap_amplitude is None:
        self.z_swap_amplitude = 0.
      if self.pelvis_offset is None:
        self.pelvis_offset = 0.
      if self.hip_pitch_offset is None:
        self.hip_pitch_offset = 0.
    else:
      self.init_x_offset = 0.
      self.init_y_offset = 0.
      self.init_z_offset = 0.
      self.init_roll_offset = 0.
      self.init_pitch_offset = 0.
      self.init_yaw_offset = 0.
      self.period_time = 0.
      self.dsp_ratio = 0.
      self.step_fb_ratio = 0.
      self.period_times = 0
      self.x_move_amplitude = 0.
      self.y_move_amplitude = 0.
      self.z_move_amplitude = 0.
      self.angle_move_amplitude = 0.
      self.move_aim_on = False
      self.arm_swing_gain = 0.
      self.y_swap_amplitude = 0.
      self.z_swap_amplitude = 0.
      self.pelvis_offset = 0.
      self.hip_pitch_offset = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_9fI4fB5f().pack(_x.init_x_offset, _x.init_y_offset, _x.init_z_offset, _x.init_roll_offset, _x.init_pitch_offset, _x.init_yaw_offset, _x.period_time, _x.dsp_ratio, _x.step_fb_ratio, _x.period_times, _x.x_move_amplitude, _x.y_move_amplitude, _x.z_move_amplitude, _x.angle_move_amplitude, _x.move_aim_on, _x.arm_swing_gain, _x.y_swap_amplitude, _x.z_swap_amplitude, _x.pelvis_offset, _x.hip_pitch_offset))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 77
      (_x.init_x_offset, _x.init_y_offset, _x.init_z_offset, _x.init_roll_offset, _x.init_pitch_offset, _x.init_yaw_offset, _x.period_time, _x.dsp_ratio, _x.step_fb_ratio, _x.period_times, _x.x_move_amplitude, _x.y_move_amplitude, _x.z_move_amplitude, _x.angle_move_amplitude, _x.move_aim_on, _x.arm_swing_gain, _x.y_swap_amplitude, _x.z_swap_amplitude, _x.pelvis_offset, _x.hip_pitch_offset,) = _get_struct_9fI4fB5f().unpack(str[start:end])
      self.move_aim_on = bool(self.move_aim_on)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_9fI4fB5f().pack(_x.init_x_offset, _x.init_y_offset, _x.init_z_offset, _x.init_roll_offset, _x.init_pitch_offset, _x.init_yaw_offset, _x.period_time, _x.dsp_ratio, _x.step_fb_ratio, _x.period_times, _x.x_move_amplitude, _x.y_move_amplitude, _x.z_move_amplitude, _x.angle_move_amplitude, _x.move_aim_on, _x.arm_swing_gain, _x.y_swap_amplitude, _x.z_swap_amplitude, _x.pelvis_offset, _x.hip_pitch_offset))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 77
      (_x.init_x_offset, _x.init_y_offset, _x.init_z_offset, _x.init_roll_offset, _x.init_pitch_offset, _x.init_yaw_offset, _x.period_time, _x.dsp_ratio, _x.step_fb_ratio, _x.period_times, _x.x_move_amplitude, _x.y_move_amplitude, _x.z_move_amplitude, _x.angle_move_amplitude, _x.move_aim_on, _x.arm_swing_gain, _x.y_swap_amplitude, _x.z_swap_amplitude, _x.pelvis_offset, _x.hip_pitch_offset,) = _get_struct_9fI4fB5f().unpack(str[start:end])
      self.move_aim_on = bool(self.move_aim_on)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_9fI4fB5f = None
def _get_struct_9fI4fB5f():
    global _struct_9fI4fB5f
    if _struct_9fI4fB5f is None:
        _struct_9fI4fB5f = struct.Struct("<9fI4fB5f")
    return _struct_9fI4fB5f
