// Generated by gencpp from file ros_robot_controller/BusServoState.msg
// DO NOT EDIT!


#ifndef ROS_ROBOT_CONTROLLER_MESSAGE_BUSSERVOSTATE_H
#define ROS_ROBOT_CONTROLLER_MESSAGE_BUSSERVOSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_robot_controller
{
template <class ContainerAllocator>
struct BusServoState_
{
  typedef BusServoState_<ContainerAllocator> Type;

  BusServoState_()
    : present_id()
    , target_id()
    , position()
    , offset()
    , voltage()
    , temperature()
    , position_limit()
    , voltage_limit()
    , max_temperature_limit()
    , enable_torque()
    , save_offset()
    , stop()  {
    }
  BusServoState_(const ContainerAllocator& _alloc)
    : present_id(_alloc)
    , target_id(_alloc)
    , position(_alloc)
    , offset(_alloc)
    , voltage(_alloc)
    , temperature(_alloc)
    , position_limit(_alloc)
    , voltage_limit(_alloc)
    , max_temperature_limit(_alloc)
    , enable_torque(_alloc)
    , save_offset(_alloc)
    , stop(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _present_id_type;
  _present_id_type present_id;

   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _target_id_type;
  _target_id_type target_id;

   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _position_type;
  _position_type position;

   typedef std::vector<int16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int16_t>> _offset_type;
  _offset_type offset;

   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _voltage_type;
  _voltage_type voltage;

   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _temperature_type;
  _temperature_type temperature;

   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _position_limit_type;
  _position_limit_type position_limit;

   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _voltage_limit_type;
  _voltage_limit_type voltage_limit;

   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _max_temperature_limit_type;
  _max_temperature_limit_type max_temperature_limit;

   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _enable_torque_type;
  _enable_torque_type enable_torque;

   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _save_offset_type;
  _save_offset_type save_offset;

   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _stop_type;
  _stop_type stop;





  typedef boost::shared_ptr< ::ros_robot_controller::BusServoState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_robot_controller::BusServoState_<ContainerAllocator> const> ConstPtr;

}; // struct BusServoState_

typedef ::ros_robot_controller::BusServoState_<std::allocator<void> > BusServoState;

typedef boost::shared_ptr< ::ros_robot_controller::BusServoState > BusServoStatePtr;
typedef boost::shared_ptr< ::ros_robot_controller::BusServoState const> BusServoStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_robot_controller::BusServoState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_robot_controller::BusServoState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_robot_controller::BusServoState_<ContainerAllocator1> & lhs, const ::ros_robot_controller::BusServoState_<ContainerAllocator2> & rhs)
{
  return lhs.present_id == rhs.present_id &&
    lhs.target_id == rhs.target_id &&
    lhs.position == rhs.position &&
    lhs.offset == rhs.offset &&
    lhs.voltage == rhs.voltage &&
    lhs.temperature == rhs.temperature &&
    lhs.position_limit == rhs.position_limit &&
    lhs.voltage_limit == rhs.voltage_limit &&
    lhs.max_temperature_limit == rhs.max_temperature_limit &&
    lhs.enable_torque == rhs.enable_torque &&
    lhs.save_offset == rhs.save_offset &&
    lhs.stop == rhs.stop;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_robot_controller::BusServoState_<ContainerAllocator1> & lhs, const ::ros_robot_controller::BusServoState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_robot_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_robot_controller::BusServoState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_robot_controller::BusServoState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_robot_controller::BusServoState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_robot_controller::BusServoState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_robot_controller::BusServoState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_robot_controller::BusServoState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_robot_controller::BusServoState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "77c375d1ab7f4d88380638703e2dbdbc";
  }

  static const char* value(const ::ros_robot_controller::BusServoState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x77c375d1ab7f4d88ULL;
  static const uint64_t static_value2 = 0x380638703e2dbdbcULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_robot_controller::BusServoState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_robot_controller/BusServoState";
  }

  static const char* value(const ::ros_robot_controller::BusServoState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_robot_controller::BusServoState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16[] present_id\n"
"uint16[] target_id\n"
"uint16[] position\n"
"int16[] offset\n"
"uint16[] voltage\n"
"uint16[] temperature\n"
"uint16[] position_limit\n"
"uint16[] voltage_limit\n"
"uint16[] max_temperature_limit\n"
"uint16[] enable_torque\n"
"uint16[] save_offset\n"
"uint16[] stop\n"
"\n"
;
  }

  static const char* value(const ::ros_robot_controller::BusServoState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_robot_controller::BusServoState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.present_id);
      stream.next(m.target_id);
      stream.next(m.position);
      stream.next(m.offset);
      stream.next(m.voltage);
      stream.next(m.temperature);
      stream.next(m.position_limit);
      stream.next(m.voltage_limit);
      stream.next(m.max_temperature_limit);
      stream.next(m.enable_torque);
      stream.next(m.save_offset);
      stream.next(m.stop);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BusServoState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_robot_controller::BusServoState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_robot_controller::BusServoState_<ContainerAllocator>& v)
  {
    s << indent << "present_id[]" << std::endl;
    for (size_t i = 0; i < v.present_id.size(); ++i)
    {
      s << indent << "  present_id[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.present_id[i]);
    }
    s << indent << "target_id[]" << std::endl;
    for (size_t i = 0; i < v.target_id.size(); ++i)
    {
      s << indent << "  target_id[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.target_id[i]);
    }
    s << indent << "position[]" << std::endl;
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      s << indent << "  position[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.position[i]);
    }
    s << indent << "offset[]" << std::endl;
    for (size_t i = 0; i < v.offset.size(); ++i)
    {
      s << indent << "  offset[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.offset[i]);
    }
    s << indent << "voltage[]" << std::endl;
    for (size_t i = 0; i < v.voltage.size(); ++i)
    {
      s << indent << "  voltage[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.voltage[i]);
    }
    s << indent << "temperature[]" << std::endl;
    for (size_t i = 0; i < v.temperature.size(); ++i)
    {
      s << indent << "  temperature[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.temperature[i]);
    }
    s << indent << "position_limit[]" << std::endl;
    for (size_t i = 0; i < v.position_limit.size(); ++i)
    {
      s << indent << "  position_limit[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.position_limit[i]);
    }
    s << indent << "voltage_limit[]" << std::endl;
    for (size_t i = 0; i < v.voltage_limit.size(); ++i)
    {
      s << indent << "  voltage_limit[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.voltage_limit[i]);
    }
    s << indent << "max_temperature_limit[]" << std::endl;
    for (size_t i = 0; i < v.max_temperature_limit.size(); ++i)
    {
      s << indent << "  max_temperature_limit[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.max_temperature_limit[i]);
    }
    s << indent << "enable_torque[]" << std::endl;
    for (size_t i = 0; i < v.enable_torque.size(); ++i)
    {
      s << indent << "  enable_torque[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.enable_torque[i]);
    }
    s << indent << "save_offset[]" << std::endl;
    for (size_t i = 0; i < v.save_offset.size(); ++i)
    {
      s << indent << "  save_offset[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.save_offset[i]);
    }
    s << indent << "stop[]" << std::endl;
    for (size_t i = 0; i < v.stop.size(); ++i)
    {
      s << indent << "  stop[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.stop[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_ROBOT_CONTROLLER_MESSAGE_BUSSERVOSTATE_H
