// Generated by gencpp from file ros_robot_controller/BusServoPosition.msg
// DO NOT EDIT!


#ifndef ROS_ROBOT_CONTROLLER_MESSAGE_BUSSERVOPOSITION_H
#define ROS_ROBOT_CONTROLLER_MESSAGE_BUSSERVOPOSITION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_robot_controller
{
template <class ContainerAllocator>
struct BusServoPosition_
{
  typedef BusServoPosition_<ContainerAllocator> Type;

  BusServoPosition_()
    : id(0)
    , position(0)  {
    }
  BusServoPosition_(const ContainerAllocator& _alloc)
    : id(0)
    , position(0)  {
  (void)_alloc;
    }



   typedef uint16_t _id_type;
  _id_type id;

   typedef uint16_t _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::ros_robot_controller::BusServoPosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_robot_controller::BusServoPosition_<ContainerAllocator> const> ConstPtr;

}; // struct BusServoPosition_

typedef ::ros_robot_controller::BusServoPosition_<std::allocator<void> > BusServoPosition;

typedef boost::shared_ptr< ::ros_robot_controller::BusServoPosition > BusServoPositionPtr;
typedef boost::shared_ptr< ::ros_robot_controller::BusServoPosition const> BusServoPositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_robot_controller::BusServoPosition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_robot_controller::BusServoPosition_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_robot_controller::BusServoPosition_<ContainerAllocator1> & lhs, const ::ros_robot_controller::BusServoPosition_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.position == rhs.position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_robot_controller::BusServoPosition_<ContainerAllocator1> & lhs, const ::ros_robot_controller::BusServoPosition_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_robot_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_robot_controller::BusServoPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_robot_controller::BusServoPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_robot_controller::BusServoPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_robot_controller::BusServoPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_robot_controller::BusServoPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_robot_controller::BusServoPosition_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_robot_controller::BusServoPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f6c99c1d923607c02ca92f7b01135d3e";
  }

  static const char* value(const ::ros_robot_controller::BusServoPosition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf6c99c1d923607c0ULL;
  static const uint64_t static_value2 = 0x2ca92f7b01135d3eULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_robot_controller::BusServoPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_robot_controller/BusServoPosition";
  }

  static const char* value(const ::ros_robot_controller::BusServoPosition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_robot_controller::BusServoPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 id\n"
"uint16 position\n"
;
  }

  static const char* value(const ::ros_robot_controller::BusServoPosition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_robot_controller::BusServoPosition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BusServoPosition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_robot_controller::BusServoPosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_robot_controller::BusServoPosition_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.id);
    s << indent << "position: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_ROBOT_CONTROLLER_MESSAGE_BUSSERVOPOSITION_H
