// Generated by gencpp from file ros_robot_controller/ButtonState.msg
// DO NOT EDIT!


#ifndef ROS_ROBOT_CONTROLLER_MESSAGE_BUTTONSTATE_H
#define ROS_ROBOT_CONTROLLER_MESSAGE_BUTTONSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_robot_controller
{
template <class ContainerAllocator>
struct ButtonState_
{
  typedef ButtonState_<ContainerAllocator> Type;

  ButtonState_()
    : id(0)
    , state(0)  {
    }
  ButtonState_(const ContainerAllocator& _alloc)
    : id(0)
    , state(0)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef uint8_t _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::ros_robot_controller::ButtonState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_robot_controller::ButtonState_<ContainerAllocator> const> ConstPtr;

}; // struct ButtonState_

typedef ::ros_robot_controller::ButtonState_<std::allocator<void> > ButtonState;

typedef boost::shared_ptr< ::ros_robot_controller::ButtonState > ButtonStatePtr;
typedef boost::shared_ptr< ::ros_robot_controller::ButtonState const> ButtonStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_robot_controller::ButtonState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_robot_controller::ButtonState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_robot_controller::ButtonState_<ContainerAllocator1> & lhs, const ::ros_robot_controller::ButtonState_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_robot_controller::ButtonState_<ContainerAllocator1> & lhs, const ::ros_robot_controller::ButtonState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_robot_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_robot_controller::ButtonState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_robot_controller::ButtonState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_robot_controller::ButtonState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_robot_controller::ButtonState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_robot_controller::ButtonState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_robot_controller::ButtonState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_robot_controller::ButtonState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b030084e787148466c67bf3e2ec970c0";
  }

  static const char* value(const ::ros_robot_controller::ButtonState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb030084e78714846ULL;
  static const uint64_t static_value2 = 0x6c67bf3e2ec970c0ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_robot_controller::ButtonState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_robot_controller/ButtonState";
  }

  static const char* value(const ::ros_robot_controller::ButtonState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_robot_controller::ButtonState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n"
"uint8 state\n"
;
  }

  static const char* value(const ::ros_robot_controller::ButtonState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_robot_controller::ButtonState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ButtonState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_robot_controller::ButtonState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_robot_controller::ButtonState_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_ROBOT_CONTROLLER_MESSAGE_BUTTONSTATE_H
