// Generated by gencpp from file ros_robot_controller/GetBusServosPositionResponse.msg
// DO NOT EDIT!


#ifndef ROS_ROBOT_CONTROLLER_MESSAGE_GETBUSSERVOSPOSITIONRESPONSE_H
#define ROS_ROBOT_CONTROLLER_MESSAGE_GETBUSSERVOSPOSITIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ros_robot_controller/BusServoPosition.h>

namespace ros_robot_controller
{
template <class ContainerAllocator>
struct GetBusServosPositionResponse_
{
  typedef GetBusServosPositionResponse_<ContainerAllocator> Type;

  GetBusServosPositionResponse_()
    : success(false)
    , position()  {
    }
  GetBusServosPositionResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , position(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::vector< ::ros_robot_controller::BusServoPosition_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::ros_robot_controller::BusServoPosition_<ContainerAllocator> >> _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::ros_robot_controller::GetBusServosPositionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_robot_controller::GetBusServosPositionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetBusServosPositionResponse_

typedef ::ros_robot_controller::GetBusServosPositionResponse_<std::allocator<void> > GetBusServosPositionResponse;

typedef boost::shared_ptr< ::ros_robot_controller::GetBusServosPositionResponse > GetBusServosPositionResponsePtr;
typedef boost::shared_ptr< ::ros_robot_controller::GetBusServosPositionResponse const> GetBusServosPositionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_robot_controller::GetBusServosPositionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_robot_controller::GetBusServosPositionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_robot_controller::GetBusServosPositionResponse_<ContainerAllocator1> & lhs, const ::ros_robot_controller::GetBusServosPositionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.position == rhs.position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_robot_controller::GetBusServosPositionResponse_<ContainerAllocator1> & lhs, const ::ros_robot_controller::GetBusServosPositionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_robot_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_robot_controller::GetBusServosPositionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_robot_controller::GetBusServosPositionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_robot_controller::GetBusServosPositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_robot_controller::GetBusServosPositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_robot_controller::GetBusServosPositionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_robot_controller::GetBusServosPositionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_robot_controller::GetBusServosPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c9b64b31d3ead9df21dff9cadcf7b948";
  }

  static const char* value(const ::ros_robot_controller::GetBusServosPositionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc9b64b31d3ead9dfULL;
  static const uint64_t static_value2 = 0x21dff9cadcf7b948ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_robot_controller::GetBusServosPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_robot_controller/GetBusServosPositionResponse";
  }

  static const char* value(const ::ros_robot_controller::GetBusServosPositionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_robot_controller::GetBusServosPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"ros_robot_controller/BusServoPosition[] position\n"
"\n"
"\n"
"================================================================================\n"
"MSG: ros_robot_controller/BusServoPosition\n"
"uint16 id\n"
"uint16 position\n"
;
  }

  static const char* value(const ::ros_robot_controller::GetBusServosPositionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_robot_controller::GetBusServosPositionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetBusServosPositionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_robot_controller::GetBusServosPositionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_robot_controller::GetBusServosPositionResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "position[]" << std::endl;
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      s << indent << "  position[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ros_robot_controller::BusServoPosition_<ContainerAllocator> >::stream(s, indent + "    ", v.position[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_ROBOT_CONTROLLER_MESSAGE_GETBUSSERVOSPOSITIONRESPONSE_H
