// Generated by gencpp from file ros_robot_controller/GetBusServoCmd.msg
// DO NOT EDIT!


#ifndef ROS_ROBOT_CONTROLLER_MESSAGE_GETBUSSERVOCMD_H
#define ROS_ROBOT_CONTROLLER_MESSAGE_GETBUSSERVOCMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_robot_controller
{
template <class ContainerAllocator>
struct GetBusServoCmd_
{
  typedef GetBusServoCmd_<ContainerAllocator> Type;

  GetBusServoCmd_()
    : id(0)
    , get_id(0)
    , get_position(0)
    , get_offset(0)
    , get_voltage(0)
    , get_temperature(0)
    , get_position_limit(0)
    , get_voltage_limit(0)
    , get_max_temperature_limit(0)
    , get_torque_state(0)  {
    }
  GetBusServoCmd_(const ContainerAllocator& _alloc)
    : id(0)
    , get_id(0)
    , get_position(0)
    , get_offset(0)
    , get_voltage(0)
    , get_temperature(0)
    , get_position_limit(0)
    , get_voltage_limit(0)
    , get_max_temperature_limit(0)
    , get_torque_state(0)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef uint8_t _get_id_type;
  _get_id_type get_id;

   typedef uint8_t _get_position_type;
  _get_position_type get_position;

   typedef uint8_t _get_offset_type;
  _get_offset_type get_offset;

   typedef uint8_t _get_voltage_type;
  _get_voltage_type get_voltage;

   typedef uint8_t _get_temperature_type;
  _get_temperature_type get_temperature;

   typedef uint8_t _get_position_limit_type;
  _get_position_limit_type get_position_limit;

   typedef uint8_t _get_voltage_limit_type;
  _get_voltage_limit_type get_voltage_limit;

   typedef uint8_t _get_max_temperature_limit_type;
  _get_max_temperature_limit_type get_max_temperature_limit;

   typedef uint8_t _get_torque_state_type;
  _get_torque_state_type get_torque_state;





  typedef boost::shared_ptr< ::ros_robot_controller::GetBusServoCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_robot_controller::GetBusServoCmd_<ContainerAllocator> const> ConstPtr;

}; // struct GetBusServoCmd_

typedef ::ros_robot_controller::GetBusServoCmd_<std::allocator<void> > GetBusServoCmd;

typedef boost::shared_ptr< ::ros_robot_controller::GetBusServoCmd > GetBusServoCmdPtr;
typedef boost::shared_ptr< ::ros_robot_controller::GetBusServoCmd const> GetBusServoCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_robot_controller::GetBusServoCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_robot_controller::GetBusServoCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_robot_controller::GetBusServoCmd_<ContainerAllocator1> & lhs, const ::ros_robot_controller::GetBusServoCmd_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.get_id == rhs.get_id &&
    lhs.get_position == rhs.get_position &&
    lhs.get_offset == rhs.get_offset &&
    lhs.get_voltage == rhs.get_voltage &&
    lhs.get_temperature == rhs.get_temperature &&
    lhs.get_position_limit == rhs.get_position_limit &&
    lhs.get_voltage_limit == rhs.get_voltage_limit &&
    lhs.get_max_temperature_limit == rhs.get_max_temperature_limit &&
    lhs.get_torque_state == rhs.get_torque_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_robot_controller::GetBusServoCmd_<ContainerAllocator1> & lhs, const ::ros_robot_controller::GetBusServoCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_robot_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_robot_controller::GetBusServoCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_robot_controller::GetBusServoCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_robot_controller::GetBusServoCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_robot_controller::GetBusServoCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_robot_controller::GetBusServoCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_robot_controller::GetBusServoCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_robot_controller::GetBusServoCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "18e5c6926d8d8fbfd6f905fb9d21ff40";
  }

  static const char* value(const ::ros_robot_controller::GetBusServoCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x18e5c6926d8d8fbfULL;
  static const uint64_t static_value2 = 0xd6f905fb9d21ff40ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_robot_controller::GetBusServoCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_robot_controller/GetBusServoCmd";
  }

  static const char* value(const ::ros_robot_controller::GetBusServoCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_robot_controller::GetBusServoCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n"
"uint8 get_id\n"
"uint8 get_position\n"
"uint8 get_offset\n"
"uint8 get_voltage\n"
"uint8 get_temperature\n"
"uint8 get_position_limit\n"
"uint8 get_voltage_limit\n"
"uint8 get_max_temperature_limit\n"
"uint8 get_torque_state\n"
;
  }

  static const char* value(const ::ros_robot_controller::GetBusServoCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_robot_controller::GetBusServoCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.get_id);
      stream.next(m.get_position);
      stream.next(m.get_offset);
      stream.next(m.get_voltage);
      stream.next(m.get_temperature);
      stream.next(m.get_position_limit);
      stream.next(m.get_voltage_limit);
      stream.next(m.get_max_temperature_limit);
      stream.next(m.get_torque_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetBusServoCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_robot_controller::GetBusServoCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_robot_controller::GetBusServoCmd_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "get_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.get_id);
    s << indent << "get_position: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.get_position);
    s << indent << "get_offset: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.get_offset);
    s << indent << "get_voltage: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.get_voltage);
    s << indent << "get_temperature: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.get_temperature);
    s << indent << "get_position_limit: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.get_position_limit);
    s << indent << "get_voltage_limit: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.get_voltage_limit);
    s << indent << "get_max_temperature_limit: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.get_max_temperature_limit);
    s << indent << "get_torque_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.get_torque_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_ROBOT_CONTROLLER_MESSAGE_GETBUSSERVOCMD_H
