// Generated by gencpp from file ros_robot_controller/GetBusServosPositionRequest.msg
// DO NOT EDIT!


#ifndef ROS_ROBOT_CONTROLLER_MESSAGE_GETBUSSERVOSPOSITIONREQUEST_H
#define ROS_ROBOT_CONTROLLER_MESSAGE_GETBUSSERVOSPOSITIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_robot_controller
{
template <class ContainerAllocator>
struct GetBusServosPositionRequest_
{
  typedef GetBusServosPositionRequest_<ContainerAllocator> Type;

  GetBusServosPositionRequest_()
    : id()  {
    }
  GetBusServosPositionRequest_(const ContainerAllocator& _alloc)
    : id(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::ros_robot_controller::GetBusServosPositionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_robot_controller::GetBusServosPositionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetBusServosPositionRequest_

typedef ::ros_robot_controller::GetBusServosPositionRequest_<std::allocator<void> > GetBusServosPositionRequest;

typedef boost::shared_ptr< ::ros_robot_controller::GetBusServosPositionRequest > GetBusServosPositionRequestPtr;
typedef boost::shared_ptr< ::ros_robot_controller::GetBusServosPositionRequest const> GetBusServosPositionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_robot_controller::GetBusServosPositionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_robot_controller::GetBusServosPositionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_robot_controller::GetBusServosPositionRequest_<ContainerAllocator1> & lhs, const ::ros_robot_controller::GetBusServosPositionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_robot_controller::GetBusServosPositionRequest_<ContainerAllocator1> & lhs, const ::ros_robot_controller::GetBusServosPositionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_robot_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_robot_controller::GetBusServosPositionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_robot_controller::GetBusServosPositionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_robot_controller::GetBusServosPositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_robot_controller::GetBusServosPositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_robot_controller::GetBusServosPositionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_robot_controller::GetBusServosPositionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_robot_controller::GetBusServosPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2e2affb9bc5b5d9659bd819a1bcaeab9";
  }

  static const char* value(const ::ros_robot_controller::GetBusServosPositionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2e2affb9bc5b5d96ULL;
  static const uint64_t static_value2 = 0x59bd819a1bcaeab9ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_robot_controller::GetBusServosPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_robot_controller/GetBusServosPositionRequest";
  }

  static const char* value(const ::ros_robot_controller::GetBusServosPositionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_robot_controller::GetBusServosPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8[] id\n"
;
  }

  static const char* value(const ::ros_robot_controller::GetBusServosPositionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_robot_controller::GetBusServosPositionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetBusServosPositionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_robot_controller::GetBusServosPositionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_robot_controller::GetBusServosPositionRequest_<ContainerAllocator>& v)
  {
    s << indent << "id[]" << std::endl;
    for (size_t i = 0; i < v.id.size(); ++i)
    {
      s << indent << "  id[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.id[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_ROBOT_CONTROLLER_MESSAGE_GETBUSSERVOSPOSITIONREQUEST_H
