// Generated by gencpp from file ros_robot_controller/GetBusServoStateRequest.msg
// DO NOT EDIT!


#ifndef ROS_ROBOT_CONTROLLER_MESSAGE_GETBUSSERVOSTATEREQUEST_H
#define ROS_ROBOT_CONTROLLER_MESSAGE_GETBUSSERVOSTATEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ros_robot_controller/GetBusServoCmd.h>

namespace ros_robot_controller
{
template <class ContainerAllocator>
struct GetBusServoStateRequest_
{
  typedef GetBusServoStateRequest_<ContainerAllocator> Type;

  GetBusServoStateRequest_()
    : cmd()  {
    }
  GetBusServoStateRequest_(const ContainerAllocator& _alloc)
    : cmd(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::ros_robot_controller::GetBusServoCmd_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::ros_robot_controller::GetBusServoCmd_<ContainerAllocator> >> _cmd_type;
  _cmd_type cmd;





  typedef boost::shared_ptr< ::ros_robot_controller::GetBusServoStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_robot_controller::GetBusServoStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetBusServoStateRequest_

typedef ::ros_robot_controller::GetBusServoStateRequest_<std::allocator<void> > GetBusServoStateRequest;

typedef boost::shared_ptr< ::ros_robot_controller::GetBusServoStateRequest > GetBusServoStateRequestPtr;
typedef boost::shared_ptr< ::ros_robot_controller::GetBusServoStateRequest const> GetBusServoStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_robot_controller::GetBusServoStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_robot_controller::GetBusServoStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_robot_controller::GetBusServoStateRequest_<ContainerAllocator1> & lhs, const ::ros_robot_controller::GetBusServoStateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.cmd == rhs.cmd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_robot_controller::GetBusServoStateRequest_<ContainerAllocator1> & lhs, const ::ros_robot_controller::GetBusServoStateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_robot_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_robot_controller::GetBusServoStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_robot_controller::GetBusServoStateRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_robot_controller::GetBusServoStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_robot_controller::GetBusServoStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_robot_controller::GetBusServoStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_robot_controller::GetBusServoStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_robot_controller::GetBusServoStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "379df0c3465ba9e18d983cc4bb700ccb";
  }

  static const char* value(const ::ros_robot_controller::GetBusServoStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x379df0c3465ba9e1ULL;
  static const uint64_t static_value2 = 0x8d983cc4bb700ccbULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_robot_controller::GetBusServoStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_robot_controller/GetBusServoStateRequest";
  }

  static const char* value(const ::ros_robot_controller::GetBusServoStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_robot_controller::GetBusServoStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_robot_controller/GetBusServoCmd[] cmd\n"
"\n"
"================================================================================\n"
"MSG: ros_robot_controller/GetBusServoCmd\n"
"uint8 id\n"
"uint8 get_id\n"
"uint8 get_position\n"
"uint8 get_offset\n"
"uint8 get_voltage\n"
"uint8 get_temperature\n"
"uint8 get_position_limit\n"
"uint8 get_voltage_limit\n"
"uint8 get_max_temperature_limit\n"
"uint8 get_torque_state\n"
;
  }

  static const char* value(const ::ros_robot_controller::GetBusServoStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_robot_controller::GetBusServoStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetBusServoStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_robot_controller::GetBusServoStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_robot_controller::GetBusServoStateRequest_<ContainerAllocator>& v)
  {
    s << indent << "cmd[]" << std::endl;
    for (size_t i = 0; i < v.cmd.size(); ++i)
    {
      s << indent << "  cmd[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ros_robot_controller::GetBusServoCmd_<ContainerAllocator> >::stream(s, indent + "    ", v.cmd[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_ROBOT_CONTROLLER_MESSAGE_GETBUSSERVOSTATEREQUEST_H
