// Generated by gencpp from file ros_robot_controller/GetBusServoState.msg
// DO NOT EDIT!


#ifndef ROS_ROBOT_CONTROLLER_MESSAGE_GETBUSSERVOSTATE_H
#define ROS_ROBOT_CONTROLLER_MESSAGE_GETBUSSERVOSTATE_H

#include <ros/service_traits.h>


#include <ros_robot_controller/GetBusServoStateRequest.h>
#include <ros_robot_controller/GetBusServoStateResponse.h>


namespace ros_robot_controller
{

struct GetBusServoState
{

typedef GetBusServoStateRequest Request;
typedef GetBusServoStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetBusServoState
} // namespace ros_robot_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_robot_controller::GetBusServoState > {
  static const char* value()
  {
    return "54f81ea2fc5cd9bb899d788802438b6e";
  }

  static const char* value(const ::ros_robot_controller::GetBusServoState&) { return value(); }
};

template<>
struct DataType< ::ros_robot_controller::GetBusServoState > {
  static const char* value()
  {
    return "ros_robot_controller/GetBusServoState";
  }

  static const char* value(const ::ros_robot_controller::GetBusServoState&) { return value(); }
};


// service_traits::MD5Sum< ::ros_robot_controller::GetBusServoStateRequest> should match
// service_traits::MD5Sum< ::ros_robot_controller::GetBusServoState >
template<>
struct MD5Sum< ::ros_robot_controller::GetBusServoStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_robot_controller::GetBusServoState >::value();
  }
  static const char* value(const ::ros_robot_controller::GetBusServoStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_robot_controller::GetBusServoStateRequest> should match
// service_traits::DataType< ::ros_robot_controller::GetBusServoState >
template<>
struct DataType< ::ros_robot_controller::GetBusServoStateRequest>
{
  static const char* value()
  {
    return DataType< ::ros_robot_controller::GetBusServoState >::value();
  }
  static const char* value(const ::ros_robot_controller::GetBusServoStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_robot_controller::GetBusServoStateResponse> should match
// service_traits::MD5Sum< ::ros_robot_controller::GetBusServoState >
template<>
struct MD5Sum< ::ros_robot_controller::GetBusServoStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_robot_controller::GetBusServoState >::value();
  }
  static const char* value(const ::ros_robot_controller::GetBusServoStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_robot_controller::GetBusServoStateResponse> should match
// service_traits::DataType< ::ros_robot_controller::GetBusServoState >
template<>
struct DataType< ::ros_robot_controller::GetBusServoStateResponse>
{
  static const char* value()
  {
    return DataType< ::ros_robot_controller::GetBusServoState >::value();
  }
  static const char* value(const ::ros_robot_controller::GetBusServoStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_ROBOT_CONTROLLER_MESSAGE_GETBUSSERVOSTATE_H
