// Generated by gencpp from file ros_robot_controller/GetBusServosPosition.msg
// DO NOT EDIT!


#ifndef ROS_ROBOT_CONTROLLER_MESSAGE_GETBUSSERVOSPOSITION_H
#define ROS_ROBOT_CONTROLLER_MESSAGE_GETBUSSERVOSPOSITION_H

#include <ros/service_traits.h>


#include <ros_robot_controller/GetBusServosPositionRequest.h>
#include <ros_robot_controller/GetBusServosPositionResponse.h>


namespace ros_robot_controller
{

struct GetBusServosPosition
{

typedef GetBusServosPositionRequest Request;
typedef GetBusServosPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetBusServosPosition
} // namespace ros_robot_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_robot_controller::GetBusServosPosition > {
  static const char* value()
  {
    return "3c9b3df543d6a1087f63caf890b57f1c";
  }

  static const char* value(const ::ros_robot_controller::GetBusServosPosition&) { return value(); }
};

template<>
struct DataType< ::ros_robot_controller::GetBusServosPosition > {
  static const char* value()
  {
    return "ros_robot_controller/GetBusServosPosition";
  }

  static const char* value(const ::ros_robot_controller::GetBusServosPosition&) { return value(); }
};


// service_traits::MD5Sum< ::ros_robot_controller::GetBusServosPositionRequest> should match
// service_traits::MD5Sum< ::ros_robot_controller::GetBusServosPosition >
template<>
struct MD5Sum< ::ros_robot_controller::GetBusServosPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_robot_controller::GetBusServosPosition >::value();
  }
  static const char* value(const ::ros_robot_controller::GetBusServosPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_robot_controller::GetBusServosPositionRequest> should match
// service_traits::DataType< ::ros_robot_controller::GetBusServosPosition >
template<>
struct DataType< ::ros_robot_controller::GetBusServosPositionRequest>
{
  static const char* value()
  {
    return DataType< ::ros_robot_controller::GetBusServosPosition >::value();
  }
  static const char* value(const ::ros_robot_controller::GetBusServosPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_robot_controller::GetBusServosPositionResponse> should match
// service_traits::MD5Sum< ::ros_robot_controller::GetBusServosPosition >
template<>
struct MD5Sum< ::ros_robot_controller::GetBusServosPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_robot_controller::GetBusServosPosition >::value();
  }
  static const char* value(const ::ros_robot_controller::GetBusServosPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_robot_controller::GetBusServosPositionResponse> should match
// service_traits::DataType< ::ros_robot_controller::GetBusServosPosition >
template<>
struct DataType< ::ros_robot_controller::GetBusServosPositionResponse>
{
  static const char* value()
  {
    return DataType< ::ros_robot_controller::GetBusServosPosition >::value();
  }
  static const char* value(const ::ros_robot_controller::GetBusServosPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_ROBOT_CONTROLLER_MESSAGE_GETBUSSERVOSPOSITION_H
