// Generated by gencpp from file ros_robot_controller/GetPWMServoCmd.msg
// DO NOT EDIT!


#ifndef ROS_ROBOT_CONTROLLER_MESSAGE_GETPWMSERVOCMD_H
#define ROS_ROBOT_CONTROLLER_MESSAGE_GETPWMSERVOCMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_robot_controller
{
template <class ContainerAllocator>
struct GetPWMServoCmd_
{
  typedef GetPWMServoCmd_<ContainerAllocator> Type;

  GetPWMServoCmd_()
    : id(0)
    , get_position(0)
    , get_offset(0)  {
    }
  GetPWMServoCmd_(const ContainerAllocator& _alloc)
    : id(0)
    , get_position(0)
    , get_offset(0)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef uint8_t _get_position_type;
  _get_position_type get_position;

   typedef uint8_t _get_offset_type;
  _get_offset_type get_offset;





  typedef boost::shared_ptr< ::ros_robot_controller::GetPWMServoCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_robot_controller::GetPWMServoCmd_<ContainerAllocator> const> ConstPtr;

}; // struct GetPWMServoCmd_

typedef ::ros_robot_controller::GetPWMServoCmd_<std::allocator<void> > GetPWMServoCmd;

typedef boost::shared_ptr< ::ros_robot_controller::GetPWMServoCmd > GetPWMServoCmdPtr;
typedef boost::shared_ptr< ::ros_robot_controller::GetPWMServoCmd const> GetPWMServoCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_robot_controller::GetPWMServoCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_robot_controller::GetPWMServoCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_robot_controller::GetPWMServoCmd_<ContainerAllocator1> & lhs, const ::ros_robot_controller::GetPWMServoCmd_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.get_position == rhs.get_position &&
    lhs.get_offset == rhs.get_offset;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_robot_controller::GetPWMServoCmd_<ContainerAllocator1> & lhs, const ::ros_robot_controller::GetPWMServoCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_robot_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_robot_controller::GetPWMServoCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_robot_controller::GetPWMServoCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_robot_controller::GetPWMServoCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_robot_controller::GetPWMServoCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_robot_controller::GetPWMServoCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_robot_controller::GetPWMServoCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_robot_controller::GetPWMServoCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b3b10a4f82a7eb6b1879d41830536868";
  }

  static const char* value(const ::ros_robot_controller::GetPWMServoCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb3b10a4f82a7eb6bULL;
  static const uint64_t static_value2 = 0x1879d41830536868ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_robot_controller::GetPWMServoCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_robot_controller/GetPWMServoCmd";
  }

  static const char* value(const ::ros_robot_controller::GetPWMServoCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_robot_controller::GetPWMServoCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n"
"uint8 get_position\n"
"uint8 get_offset\n"
;
  }

  static const char* value(const ::ros_robot_controller::GetPWMServoCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_robot_controller::GetPWMServoCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.get_position);
      stream.next(m.get_offset);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetPWMServoCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_robot_controller::GetPWMServoCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_robot_controller::GetPWMServoCmd_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "get_position: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.get_position);
    s << indent << "get_offset: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.get_offset);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_ROBOT_CONTROLLER_MESSAGE_GETPWMSERVOCMD_H
