// Generated by gencpp from file ros_robot_controller/GetPWMServoState.msg
// DO NOT EDIT!


#ifndef ROS_ROBOT_CONTROLLER_MESSAGE_GETPWMSERVOSTATE_H
#define ROS_ROBOT_CONTROLLER_MESSAGE_GETPWMSERVOSTATE_H

#include <ros/service_traits.h>


#include <ros_robot_controller/GetPWMServoStateRequest.h>
#include <ros_robot_controller/GetPWMServoStateResponse.h>


namespace ros_robot_controller
{

struct GetPWMServoState
{

typedef GetPWMServoStateRequest Request;
typedef GetPWMServoStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPWMServoState
} // namespace ros_robot_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_robot_controller::GetPWMServoState > {
  static const char* value()
  {
    return "c3e4ead166c4d391546c9de61b2654da";
  }

  static const char* value(const ::ros_robot_controller::GetPWMServoState&) { return value(); }
};

template<>
struct DataType< ::ros_robot_controller::GetPWMServoState > {
  static const char* value()
  {
    return "ros_robot_controller/GetPWMServoState";
  }

  static const char* value(const ::ros_robot_controller::GetPWMServoState&) { return value(); }
};


// service_traits::MD5Sum< ::ros_robot_controller::GetPWMServoStateRequest> should match
// service_traits::MD5Sum< ::ros_robot_controller::GetPWMServoState >
template<>
struct MD5Sum< ::ros_robot_controller::GetPWMServoStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_robot_controller::GetPWMServoState >::value();
  }
  static const char* value(const ::ros_robot_controller::GetPWMServoStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_robot_controller::GetPWMServoStateRequest> should match
// service_traits::DataType< ::ros_robot_controller::GetPWMServoState >
template<>
struct DataType< ::ros_robot_controller::GetPWMServoStateRequest>
{
  static const char* value()
  {
    return DataType< ::ros_robot_controller::GetPWMServoState >::value();
  }
  static const char* value(const ::ros_robot_controller::GetPWMServoStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_robot_controller::GetPWMServoStateResponse> should match
// service_traits::MD5Sum< ::ros_robot_controller::GetPWMServoState >
template<>
struct MD5Sum< ::ros_robot_controller::GetPWMServoStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_robot_controller::GetPWMServoState >::value();
  }
  static const char* value(const ::ros_robot_controller::GetPWMServoStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_robot_controller::GetPWMServoStateResponse> should match
// service_traits::DataType< ::ros_robot_controller::GetPWMServoState >
template<>
struct DataType< ::ros_robot_controller::GetPWMServoStateResponse>
{
  static const char* value()
  {
    return DataType< ::ros_robot_controller::GetPWMServoState >::value();
  }
  static const char* value(const ::ros_robot_controller::GetPWMServoStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_ROBOT_CONTROLLER_MESSAGE_GETPWMSERVOSTATE_H
