// Generated by gencpp from file ros_robot_controller/GetPWMServoStateResponse.msg
// DO NOT EDIT!


#ifndef ROS_ROBOT_CONTROLLER_MESSAGE_GETPWMSERVOSTATERESPONSE_H
#define ROS_ROBOT_CONTROLLER_MESSAGE_GETPWMSERVOSTATERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ros_robot_controller/PWMServoState.h>

namespace ros_robot_controller
{
template <class ContainerAllocator>
struct GetPWMServoStateResponse_
{
  typedef GetPWMServoStateResponse_<ContainerAllocator> Type;

  GetPWMServoStateResponse_()
    : success(false)
    , state()  {
    }
  GetPWMServoStateResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , state(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::vector< ::ros_robot_controller::PWMServoState_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::ros_robot_controller::PWMServoState_<ContainerAllocator> >> _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::ros_robot_controller::GetPWMServoStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_robot_controller::GetPWMServoStateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetPWMServoStateResponse_

typedef ::ros_robot_controller::GetPWMServoStateResponse_<std::allocator<void> > GetPWMServoStateResponse;

typedef boost::shared_ptr< ::ros_robot_controller::GetPWMServoStateResponse > GetPWMServoStateResponsePtr;
typedef boost::shared_ptr< ::ros_robot_controller::GetPWMServoStateResponse const> GetPWMServoStateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_robot_controller::GetPWMServoStateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_robot_controller::GetPWMServoStateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_robot_controller::GetPWMServoStateResponse_<ContainerAllocator1> & lhs, const ::ros_robot_controller::GetPWMServoStateResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_robot_controller::GetPWMServoStateResponse_<ContainerAllocator1> & lhs, const ::ros_robot_controller::GetPWMServoStateResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_robot_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_robot_controller::GetPWMServoStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_robot_controller::GetPWMServoStateResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_robot_controller::GetPWMServoStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_robot_controller::GetPWMServoStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_robot_controller::GetPWMServoStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_robot_controller::GetPWMServoStateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_robot_controller::GetPWMServoStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f5de8affc24b5ec0291f2e1754776767";
  }

  static const char* value(const ::ros_robot_controller::GetPWMServoStateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf5de8affc24b5ec0ULL;
  static const uint64_t static_value2 = 0x291f2e1754776767ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_robot_controller::GetPWMServoStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_robot_controller/GetPWMServoStateResponse";
  }

  static const char* value(const ::ros_robot_controller::GetPWMServoStateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_robot_controller::GetPWMServoStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"ros_robot_controller/PWMServoState[] state\n"
"\n"
"\n"
"================================================================================\n"
"MSG: ros_robot_controller/PWMServoState\n"
"uint16[] id\n"
"uint16[] position\n"
"int16[] offset\n"
;
  }

  static const char* value(const ::ros_robot_controller::GetPWMServoStateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_robot_controller::GetPWMServoStateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetPWMServoStateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_robot_controller::GetPWMServoStateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_robot_controller::GetPWMServoStateResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "state[]" << std::endl;
    for (size_t i = 0; i < v.state.size(); ++i)
    {
      s << indent << "  state[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ros_robot_controller::PWMServoState_<ContainerAllocator> >::stream(s, indent + "    ", v.state[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_ROBOT_CONTROLLER_MESSAGE_GETPWMSERVOSTATERESPONSE_H
