// Generated by gencpp from file ros_robot_controller/LedState.msg
// DO NOT EDIT!


#ifndef ROS_ROBOT_CONTROLLER_MESSAGE_LEDSTATE_H
#define ROS_ROBOT_CONTROLLER_MESSAGE_LEDSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_robot_controller
{
template <class ContainerAllocator>
struct LedState_
{
  typedef LedState_<ContainerAllocator> Type;

  LedState_()
    : id(0)
    , on_time(0.0)
    , off_time(0.0)
    , repeat(0)  {
    }
  LedState_(const ContainerAllocator& _alloc)
    : id(0)
    , on_time(0.0)
    , off_time(0.0)
    , repeat(0)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef float _on_time_type;
  _on_time_type on_time;

   typedef float _off_time_type;
  _off_time_type off_time;

   typedef uint16_t _repeat_type;
  _repeat_type repeat;





  typedef boost::shared_ptr< ::ros_robot_controller::LedState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_robot_controller::LedState_<ContainerAllocator> const> ConstPtr;

}; // struct LedState_

typedef ::ros_robot_controller::LedState_<std::allocator<void> > LedState;

typedef boost::shared_ptr< ::ros_robot_controller::LedState > LedStatePtr;
typedef boost::shared_ptr< ::ros_robot_controller::LedState const> LedStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_robot_controller::LedState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_robot_controller::LedState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_robot_controller::LedState_<ContainerAllocator1> & lhs, const ::ros_robot_controller::LedState_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.on_time == rhs.on_time &&
    lhs.off_time == rhs.off_time &&
    lhs.repeat == rhs.repeat;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_robot_controller::LedState_<ContainerAllocator1> & lhs, const ::ros_robot_controller::LedState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_robot_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_robot_controller::LedState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_robot_controller::LedState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_robot_controller::LedState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_robot_controller::LedState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_robot_controller::LedState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_robot_controller::LedState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_robot_controller::LedState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aedc0628f1bc854143b196b8fbc44c35";
  }

  static const char* value(const ::ros_robot_controller::LedState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaedc0628f1bc8541ULL;
  static const uint64_t static_value2 = 0x43b196b8fbc44c35ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_robot_controller::LedState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_robot_controller/LedState";
  }

  static const char* value(const ::ros_robot_controller::LedState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_robot_controller::LedState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n"
"float32 on_time\n"
"float32 off_time\n"
"uint16 repeat\n"
;
  }

  static const char* value(const ::ros_robot_controller::LedState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_robot_controller::LedState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.on_time);
      stream.next(m.off_time);
      stream.next(m.repeat);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LedState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_robot_controller::LedState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_robot_controller::LedState_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "on_time: ";
    Printer<float>::stream(s, indent + "  ", v.on_time);
    s << indent << "off_time: ";
    Printer<float>::stream(s, indent + "  ", v.off_time);
    s << indent << "repeat: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.repeat);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_ROBOT_CONTROLLER_MESSAGE_LEDSTATE_H
