// Generated by gencpp from file ros_robot_controller/MotorState.msg
// DO NOT EDIT!


#ifndef ROS_ROBOT_CONTROLLER_MESSAGE_MOTORSTATE_H
#define ROS_ROBOT_CONTROLLER_MESSAGE_MOTORSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_robot_controller
{
template <class ContainerAllocator>
struct MotorState_
{
  typedef MotorState_<ContainerAllocator> Type;

  MotorState_()
    : id(0)
    , rps(0.0)
    , duty(0)  {
    }
  MotorState_(const ContainerAllocator& _alloc)
    : id(0)
    , rps(0.0)
    , duty(0)  {
  (void)_alloc;
    }



   typedef uint16_t _id_type;
  _id_type id;

   typedef double _rps_type;
  _rps_type rps;

   typedef int8_t _duty_type;
  _duty_type duty;





  typedef boost::shared_ptr< ::ros_robot_controller::MotorState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_robot_controller::MotorState_<ContainerAllocator> const> ConstPtr;

}; // struct MotorState_

typedef ::ros_robot_controller::MotorState_<std::allocator<void> > MotorState;

typedef boost::shared_ptr< ::ros_robot_controller::MotorState > MotorStatePtr;
typedef boost::shared_ptr< ::ros_robot_controller::MotorState const> MotorStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_robot_controller::MotorState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_robot_controller::MotorState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_robot_controller::MotorState_<ContainerAllocator1> & lhs, const ::ros_robot_controller::MotorState_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.rps == rhs.rps &&
    lhs.duty == rhs.duty;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_robot_controller::MotorState_<ContainerAllocator1> & lhs, const ::ros_robot_controller::MotorState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_robot_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_robot_controller::MotorState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_robot_controller::MotorState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_robot_controller::MotorState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_robot_controller::MotorState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_robot_controller::MotorState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_robot_controller::MotorState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_robot_controller::MotorState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d79026762feb15b0fd2b852459fe5888";
  }

  static const char* value(const ::ros_robot_controller::MotorState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd79026762feb15b0ULL;
  static const uint64_t static_value2 = 0xfd2b852459fe5888ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_robot_controller::MotorState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_robot_controller/MotorState";
  }

  static const char* value(const ::ros_robot_controller::MotorState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_robot_controller::MotorState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 id\n"
"float64 rps\n"
"int8 duty\n"
;
  }

  static const char* value(const ::ros_robot_controller::MotorState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_robot_controller::MotorState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.rps);
      stream.next(m.duty);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_robot_controller::MotorState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_robot_controller::MotorState_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.id);
    s << indent << "rps: ";
    Printer<double>::stream(s, indent + "  ", v.rps);
    s << indent << "duty: ";
    Printer<int8_t>::stream(s, indent + "  ", v.duty);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_ROBOT_CONTROLLER_MESSAGE_MOTORSTATE_H
