// Generated by gencpp from file ros_robot_controller/OLEDState.msg
// DO NOT EDIT!


#ifndef ROS_ROBOT_CONTROLLER_MESSAGE_OLEDSTATE_H
#define ROS_ROBOT_CONTROLLER_MESSAGE_OLEDSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_robot_controller
{
template <class ContainerAllocator>
struct OLEDState_
{
  typedef OLEDState_<ContainerAllocator> Type;

  OLEDState_()
    : index(0)
    , text()  {
    }
  OLEDState_(const ContainerAllocator& _alloc)
    : index(0)
    , text(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _index_type;
  _index_type index;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _text_type;
  _text_type text;





  typedef boost::shared_ptr< ::ros_robot_controller::OLEDState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_robot_controller::OLEDState_<ContainerAllocator> const> ConstPtr;

}; // struct OLEDState_

typedef ::ros_robot_controller::OLEDState_<std::allocator<void> > OLEDState;

typedef boost::shared_ptr< ::ros_robot_controller::OLEDState > OLEDStatePtr;
typedef boost::shared_ptr< ::ros_robot_controller::OLEDState const> OLEDStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_robot_controller::OLEDState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_robot_controller::OLEDState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_robot_controller::OLEDState_<ContainerAllocator1> & lhs, const ::ros_robot_controller::OLEDState_<ContainerAllocator2> & rhs)
{
  return lhs.index == rhs.index &&
    lhs.text == rhs.text;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_robot_controller::OLEDState_<ContainerAllocator1> & lhs, const ::ros_robot_controller::OLEDState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_robot_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_robot_controller::OLEDState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_robot_controller::OLEDState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_robot_controller::OLEDState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_robot_controller::OLEDState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_robot_controller::OLEDState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_robot_controller::OLEDState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_robot_controller::OLEDState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "205a1c2cc7c3057aaccb3f8bbf12e142";
  }

  static const char* value(const ::ros_robot_controller::OLEDState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x205a1c2cc7c3057aULL;
  static const uint64_t static_value2 = 0xaccb3f8bbf12e142ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_robot_controller::OLEDState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_robot_controller/OLEDState";
  }

  static const char* value(const ::ros_robot_controller::OLEDState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_robot_controller::OLEDState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 index\n"
"string text\n"
;
  }

  static const char* value(const ::ros_robot_controller::OLEDState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_robot_controller::OLEDState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.index);
      stream.next(m.text);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OLEDState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_robot_controller::OLEDState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_robot_controller::OLEDState_<ContainerAllocator>& v)
  {
    s << indent << "index: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.index);
    s << indent << "text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.text);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_ROBOT_CONTROLLER_MESSAGE_OLEDSTATE_H
