// Generated by gencpp from file ros_robot_controller/PWMServoState.msg
// DO NOT EDIT!


#ifndef ROS_ROBOT_CONTROLLER_MESSAGE_PWMSERVOSTATE_H
#define ROS_ROBOT_CONTROLLER_MESSAGE_PWMSERVOSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_robot_controller
{
template <class ContainerAllocator>
struct PWMServoState_
{
  typedef PWMServoState_<ContainerAllocator> Type;

  PWMServoState_()
    : id()
    , position()
    , offset()  {
    }
  PWMServoState_(const ContainerAllocator& _alloc)
    : id(_alloc)
    , position(_alloc)
    , offset(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _id_type;
  _id_type id;

   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _position_type;
  _position_type position;

   typedef std::vector<int16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int16_t>> _offset_type;
  _offset_type offset;





  typedef boost::shared_ptr< ::ros_robot_controller::PWMServoState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_robot_controller::PWMServoState_<ContainerAllocator> const> ConstPtr;

}; // struct PWMServoState_

typedef ::ros_robot_controller::PWMServoState_<std::allocator<void> > PWMServoState;

typedef boost::shared_ptr< ::ros_robot_controller::PWMServoState > PWMServoStatePtr;
typedef boost::shared_ptr< ::ros_robot_controller::PWMServoState const> PWMServoStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_robot_controller::PWMServoState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_robot_controller::PWMServoState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_robot_controller::PWMServoState_<ContainerAllocator1> & lhs, const ::ros_robot_controller::PWMServoState_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.position == rhs.position &&
    lhs.offset == rhs.offset;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_robot_controller::PWMServoState_<ContainerAllocator1> & lhs, const ::ros_robot_controller::PWMServoState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_robot_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_robot_controller::PWMServoState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_robot_controller::PWMServoState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_robot_controller::PWMServoState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_robot_controller::PWMServoState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_robot_controller::PWMServoState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_robot_controller::PWMServoState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_robot_controller::PWMServoState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c26a15aad910866b2e34eeadf50a1646";
  }

  static const char* value(const ::ros_robot_controller::PWMServoState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc26a15aad910866bULL;
  static const uint64_t static_value2 = 0x2e34eeadf50a1646ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_robot_controller::PWMServoState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_robot_controller/PWMServoState";
  }

  static const char* value(const ::ros_robot_controller::PWMServoState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_robot_controller::PWMServoState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16[] id\n"
"uint16[] position\n"
"int16[] offset\n"
;
  }

  static const char* value(const ::ros_robot_controller::PWMServoState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_robot_controller::PWMServoState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.position);
      stream.next(m.offset);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PWMServoState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_robot_controller::PWMServoState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_robot_controller::PWMServoState_<ContainerAllocator>& v)
  {
    s << indent << "id[]" << std::endl;
    for (size_t i = 0; i < v.id.size(); ++i)
    {
      s << indent << "  id[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.id[i]);
    }
    s << indent << "position[]" << std::endl;
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      s << indent << "  position[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.position[i]);
    }
    s << indent << "offset[]" << std::endl;
    for (size_t i = 0; i < v.offset.size(); ++i)
    {
      s << indent << "  offset[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.offset[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_ROBOT_CONTROLLER_MESSAGE_PWMSERVOSTATE_H
