// Generated by gencpp from file ros_robot_controller/RGBsState.msg
// DO NOT EDIT!


#ifndef ROS_ROBOT_CONTROLLER_MESSAGE_RGBSSTATE_H
#define ROS_ROBOT_CONTROLLER_MESSAGE_RGBSSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ros_robot_controller/RGBState.h>

namespace ros_robot_controller
{
template <class ContainerAllocator>
struct RGBsState_
{
  typedef RGBsState_<ContainerAllocator> Type;

  RGBsState_()
    : data()  {
    }
  RGBsState_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::ros_robot_controller::RGBState_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::ros_robot_controller::RGBState_<ContainerAllocator> >> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::ros_robot_controller::RGBsState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_robot_controller::RGBsState_<ContainerAllocator> const> ConstPtr;

}; // struct RGBsState_

typedef ::ros_robot_controller::RGBsState_<std::allocator<void> > RGBsState;

typedef boost::shared_ptr< ::ros_robot_controller::RGBsState > RGBsStatePtr;
typedef boost::shared_ptr< ::ros_robot_controller::RGBsState const> RGBsStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_robot_controller::RGBsState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_robot_controller::RGBsState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_robot_controller::RGBsState_<ContainerAllocator1> & lhs, const ::ros_robot_controller::RGBsState_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_robot_controller::RGBsState_<ContainerAllocator1> & lhs, const ::ros_robot_controller::RGBsState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_robot_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_robot_controller::RGBsState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_robot_controller::RGBsState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_robot_controller::RGBsState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_robot_controller::RGBsState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_robot_controller::RGBsState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_robot_controller::RGBsState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_robot_controller::RGBsState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cb5dfd3060b85c0fec6981d83d7c1830";
  }

  static const char* value(const ::ros_robot_controller::RGBsState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcb5dfd3060b85c0fULL;
  static const uint64_t static_value2 = 0xec6981d83d7c1830ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_robot_controller::RGBsState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_robot_controller/RGBsState";
  }

  static const char* value(const ::ros_robot_controller::RGBsState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_robot_controller::RGBsState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_robot_controller/RGBState[] data\n"
"\n"
"================================================================================\n"
"MSG: ros_robot_controller/RGBState\n"
"uint8 id\n"
"uint8 r\n"
"uint8 g\n"
"uint8 b\n"
;
  }

  static const char* value(const ::ros_robot_controller::RGBsState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_robot_controller::RGBsState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RGBsState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_robot_controller::RGBsState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_robot_controller::RGBsState_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ros_robot_controller::RGBState_<ContainerAllocator> >::stream(s, indent + "    ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_ROBOT_CONTROLLER_MESSAGE_RGBSSTATE_H
