// Generated by gencpp from file ros_robot_controller/RGBState.msg
// DO NOT EDIT!


#ifndef ROS_ROBOT_CONTROLLER_MESSAGE_RGBSTATE_H
#define ROS_ROBOT_CONTROLLER_MESSAGE_RGBSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_robot_controller
{
template <class ContainerAllocator>
struct RGBState_
{
  typedef RGBState_<ContainerAllocator> Type;

  RGBState_()
    : id(0)
    , r(0)
    , g(0)
    , b(0)  {
    }
  RGBState_(const ContainerAllocator& _alloc)
    : id(0)
    , r(0)
    , g(0)
    , b(0)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef uint8_t _r_type;
  _r_type r;

   typedef uint8_t _g_type;
  _g_type g;

   typedef uint8_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::ros_robot_controller::RGBState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_robot_controller::RGBState_<ContainerAllocator> const> ConstPtr;

}; // struct RGBState_

typedef ::ros_robot_controller::RGBState_<std::allocator<void> > RGBState;

typedef boost::shared_ptr< ::ros_robot_controller::RGBState > RGBStatePtr;
typedef boost::shared_ptr< ::ros_robot_controller::RGBState const> RGBStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_robot_controller::RGBState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_robot_controller::RGBState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_robot_controller::RGBState_<ContainerAllocator1> & lhs, const ::ros_robot_controller::RGBState_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.r == rhs.r &&
    lhs.g == rhs.g &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_robot_controller::RGBState_<ContainerAllocator1> & lhs, const ::ros_robot_controller::RGBState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_robot_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_robot_controller::RGBState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_robot_controller::RGBState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_robot_controller::RGBState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_robot_controller::RGBState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_robot_controller::RGBState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_robot_controller::RGBState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_robot_controller::RGBState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "343e67bfed955dda24bc6fa95587f87d";
  }

  static const char* value(const ::ros_robot_controller::RGBState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x343e67bfed955ddaULL;
  static const uint64_t static_value2 = 0x24bc6fa95587f87dULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_robot_controller::RGBState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_robot_controller/RGBState";
  }

  static const char* value(const ::ros_robot_controller::RGBState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_robot_controller::RGBState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n"
"uint8 r\n"
"uint8 g\n"
"uint8 b\n"
;
  }

  static const char* value(const ::ros_robot_controller::RGBState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_robot_controller::RGBState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.r);
      stream.next(m.g);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RGBState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_robot_controller::RGBState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_robot_controller::RGBState_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "r: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.r);
    s << indent << "g: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.g);
    s << indent << "b: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_ROBOT_CONTROLLER_MESSAGE_RGBSTATE_H
