// Generated by gencpp from file ros_robot_controller/Sbus.msg
// DO NOT EDIT!


#ifndef ROS_ROBOT_CONTROLLER_MESSAGE_SBUS_H
#define ROS_ROBOT_CONTROLLER_MESSAGE_SBUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ros_robot_controller
{
template <class ContainerAllocator>
struct Sbus_
{
  typedef Sbus_<ContainerAllocator> Type;

  Sbus_()
    : header()
    , channel()  {
    }
  Sbus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , channel(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _channel_type;
  _channel_type channel;





  typedef boost::shared_ptr< ::ros_robot_controller::Sbus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_robot_controller::Sbus_<ContainerAllocator> const> ConstPtr;

}; // struct Sbus_

typedef ::ros_robot_controller::Sbus_<std::allocator<void> > Sbus;

typedef boost::shared_ptr< ::ros_robot_controller::Sbus > SbusPtr;
typedef boost::shared_ptr< ::ros_robot_controller::Sbus const> SbusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_robot_controller::Sbus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_robot_controller::Sbus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_robot_controller::Sbus_<ContainerAllocator1> & lhs, const ::ros_robot_controller::Sbus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.channel == rhs.channel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_robot_controller::Sbus_<ContainerAllocator1> & lhs, const ::ros_robot_controller::Sbus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_robot_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_robot_controller::Sbus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_robot_controller::Sbus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_robot_controller::Sbus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_robot_controller::Sbus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_robot_controller::Sbus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_robot_controller::Sbus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_robot_controller::Sbus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "509d6343bf29722432e3278c76d6a985";
  }

  static const char* value(const ::ros_robot_controller::Sbus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x509d6343bf297224ULL;
  static const uint64_t static_value2 = 0x32e3278c76d6a985ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_robot_controller::Sbus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_robot_controller/Sbus";
  }

  static const char* value(const ::ros_robot_controller::Sbus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_robot_controller::Sbus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32[] channel\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ros_robot_controller::Sbus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_robot_controller::Sbus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.channel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Sbus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_robot_controller::Sbus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_robot_controller::Sbus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "channel[]" << std::endl;
    for (size_t i = 0; i < v.channel.size(); ++i)
    {
      s << indent << "  channel[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.channel[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_ROBOT_CONTROLLER_MESSAGE_SBUS_H
