// Generated by gencpp from file ros_robot_controller/SetBusServosPosition.msg
// DO NOT EDIT!


#ifndef ROS_ROBOT_CONTROLLER_MESSAGE_SETBUSSERVOSPOSITION_H
#define ROS_ROBOT_CONTROLLER_MESSAGE_SETBUSSERVOSPOSITION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ros_robot_controller/BusServoPosition.h>

namespace ros_robot_controller
{
template <class ContainerAllocator>
struct SetBusServosPosition_
{
  typedef SetBusServosPosition_<ContainerAllocator> Type;

  SetBusServosPosition_()
    : duration(0.0)
    , position()  {
    }
  SetBusServosPosition_(const ContainerAllocator& _alloc)
    : duration(0.0)
    , position(_alloc)  {
  (void)_alloc;
    }



   typedef double _duration_type;
  _duration_type duration;

   typedef std::vector< ::ros_robot_controller::BusServoPosition_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::ros_robot_controller::BusServoPosition_<ContainerAllocator> >> _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::ros_robot_controller::SetBusServosPosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_robot_controller::SetBusServosPosition_<ContainerAllocator> const> ConstPtr;

}; // struct SetBusServosPosition_

typedef ::ros_robot_controller::SetBusServosPosition_<std::allocator<void> > SetBusServosPosition;

typedef boost::shared_ptr< ::ros_robot_controller::SetBusServosPosition > SetBusServosPositionPtr;
typedef boost::shared_ptr< ::ros_robot_controller::SetBusServosPosition const> SetBusServosPositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_robot_controller::SetBusServosPosition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_robot_controller::SetBusServosPosition_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_robot_controller::SetBusServosPosition_<ContainerAllocator1> & lhs, const ::ros_robot_controller::SetBusServosPosition_<ContainerAllocator2> & rhs)
{
  return lhs.duration == rhs.duration &&
    lhs.position == rhs.position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_robot_controller::SetBusServosPosition_<ContainerAllocator1> & lhs, const ::ros_robot_controller::SetBusServosPosition_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_robot_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_robot_controller::SetBusServosPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_robot_controller::SetBusServosPosition_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_robot_controller::SetBusServosPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_robot_controller::SetBusServosPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_robot_controller::SetBusServosPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_robot_controller::SetBusServosPosition_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_robot_controller::SetBusServosPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ed584daec2751e0a3aa8679e2d6197b3";
  }

  static const char* value(const ::ros_robot_controller::SetBusServosPosition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xed584daec2751e0aULL;
  static const uint64_t static_value2 = 0x3aa8679e2d6197b3ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_robot_controller::SetBusServosPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_robot_controller/SetBusServosPosition";
  }

  static const char* value(const ::ros_robot_controller::SetBusServosPosition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_robot_controller::SetBusServosPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 duration\n"
"ros_robot_controller/BusServoPosition[] position\n"
"\n"
"================================================================================\n"
"MSG: ros_robot_controller/BusServoPosition\n"
"uint16 id\n"
"uint16 position\n"
;
  }

  static const char* value(const ::ros_robot_controller::SetBusServosPosition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_robot_controller::SetBusServosPosition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.duration);
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetBusServosPosition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_robot_controller::SetBusServosPosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_robot_controller::SetBusServosPosition_<ContainerAllocator>& v)
  {
    s << indent << "duration: ";
    Printer<double>::stream(s, indent + "  ", v.duration);
    s << indent << "position[]" << std::endl;
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      s << indent << "  position[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ros_robot_controller::BusServoPosition_<ContainerAllocator> >::stream(s, indent + "    ", v.position[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_ROBOT_CONTROLLER_MESSAGE_SETBUSSERVOSPOSITION_H
