// Generated by gencpp from file ros_robot_controller/SetPWMServoState.msg
// DO NOT EDIT!


#ifndef ROS_ROBOT_CONTROLLER_MESSAGE_SETPWMSERVOSTATE_H
#define ROS_ROBOT_CONTROLLER_MESSAGE_SETPWMSERVOSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ros_robot_controller/PWMServoState.h>

namespace ros_robot_controller
{
template <class ContainerAllocator>
struct SetPWMServoState_
{
  typedef SetPWMServoState_<ContainerAllocator> Type;

  SetPWMServoState_()
    : state()
    , duration(0.0)  {
    }
  SetPWMServoState_(const ContainerAllocator& _alloc)
    : state(_alloc)
    , duration(0.0)  {
  (void)_alloc;
    }



   typedef std::vector< ::ros_robot_controller::PWMServoState_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::ros_robot_controller::PWMServoState_<ContainerAllocator> >> _state_type;
  _state_type state;

   typedef double _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::ros_robot_controller::SetPWMServoState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_robot_controller::SetPWMServoState_<ContainerAllocator> const> ConstPtr;

}; // struct SetPWMServoState_

typedef ::ros_robot_controller::SetPWMServoState_<std::allocator<void> > SetPWMServoState;

typedef boost::shared_ptr< ::ros_robot_controller::SetPWMServoState > SetPWMServoStatePtr;
typedef boost::shared_ptr< ::ros_robot_controller::SetPWMServoState const> SetPWMServoStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_robot_controller::SetPWMServoState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_robot_controller::SetPWMServoState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_robot_controller::SetPWMServoState_<ContainerAllocator1> & lhs, const ::ros_robot_controller::SetPWMServoState_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state &&
    lhs.duration == rhs.duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_robot_controller::SetPWMServoState_<ContainerAllocator1> & lhs, const ::ros_robot_controller::SetPWMServoState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_robot_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_robot_controller::SetPWMServoState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_robot_controller::SetPWMServoState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_robot_controller::SetPWMServoState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_robot_controller::SetPWMServoState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_robot_controller::SetPWMServoState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_robot_controller::SetPWMServoState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_robot_controller::SetPWMServoState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "755ec4886ec626286881531bdc39b1ad";
  }

  static const char* value(const ::ros_robot_controller::SetPWMServoState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x755ec4886ec62628ULL;
  static const uint64_t static_value2 = 0x6881531bdc39b1adULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_robot_controller::SetPWMServoState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_robot_controller/SetPWMServoState";
  }

  static const char* value(const ::ros_robot_controller::SetPWMServoState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_robot_controller::SetPWMServoState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_robot_controller/PWMServoState[] state\n"
"\n"
"float64 duration\n"
"\n"
"================================================================================\n"
"MSG: ros_robot_controller/PWMServoState\n"
"uint16[] id\n"
"uint16[] position\n"
"int16[] offset\n"
;
  }

  static const char* value(const ::ros_robot_controller::SetPWMServoState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_robot_controller::SetPWMServoState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetPWMServoState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_robot_controller::SetPWMServoState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_robot_controller::SetPWMServoState_<ContainerAllocator>& v)
  {
    s << indent << "state[]" << std::endl;
    for (size_t i = 0; i < v.state.size(); ++i)
    {
      s << indent << "  state[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ros_robot_controller::PWMServoState_<ContainerAllocator> >::stream(s, indent + "    ", v.state[i]);
    }
    s << indent << "duration: ";
    Printer<double>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_ROBOT_CONTROLLER_MESSAGE_SETPWMSERVOSTATE_H
